### PR TITLE
Introduce a neo4j-security module, for auth, encryption and so on.

### PR DESCRIPTION
**Pull request by jakewins**
- Move the AuthManager down to neo4j-security, as a first step on
  a larger planned refactoring.
- Also factor out a neo4j-common module for common infrastructure
  that are currently spread across varios modules. Moving a small
  portion of that spread-out code only to support the AuthManager.

### CODE REVIEW

**Comment by benbc** [comment]
@jakewins As you mentioned elsewhere, endlessly proliferating Maven modules is a bad idea. We'd like to have fewer rather than more. Of course every time you need to do something like this the easiest thing is just to create a new module and get on with your life, so the number will increase indefinitely. How about a one-in-one-out policy?

**Comment by jakewins** [comment]
@benbc agree. I can add a second commit here that folds one of the existing utility modules into `neo4j-common`

**Comment by craigtaverner** [comment]
Regarding modules, why not put this into kernel? Auth will be fundamental to all future versions of neo4j, right? (and already is)

**Comment by spacecowboy** [comment]
@craigtaverner can we please not treat kernel as the dumping ground for everything under miscellaneous?

**Comment by spacecowboy** [comment]
@jakewins We just merged a PR that enabled findbugs: https://github.com/neo4j/neo4j/pull/6366

So you'll likely have to build with `-Doverwrite` to fix the licenses in your modules here

**Pull request merged**
