### PR TITLE
Introduce and use Java8 compatible functional interfaces

### PR DESCRIPTION
**Pull request by cleishm**
This interface is the same as available in Java 8, and should be
replaced with that interface when we begin building with Java 8.

Also includes some factory methods for useful Supplier types.

### CODE REVIEW

**Comment by tinwelint** [comment]
It sounds like it's replacing `org.neo4j.helpers.Provider`, not really `org.neo4j.function.Factory` since Factory has a contract of always creating new instances, whereas Provider hasn't, like Supplier.

**Comment by cleishm** [comment]
ok

**Comment by thobe** [comment]
Why introduce these types without them being used? What is the need for them?

**Comment by chrisvest** [comment]
@cleishm Added some comments on the individual commits.

**Comment by thobe** [comment]
haven't we already deprecated all of `org.neo4j.helpers`?

**Comment by chrisvest** [comment]
Not officially in the sense of putting the annotation on _all_ of the classes. The `org.neo4j.helpers` package is also listed in our published javadoc.

**Pull request merged**
