### PR TITLE
Add separate test project for neo4j-harness.

### PR DESCRIPTION
**Pull request by nawroth**
- Fix bug in the POM of neo4j-harness.
- Add neo4j-harness-test module.
- Improve other POM files.

### CODE REVIEW

**Comment by thobe** [comment]
I would love to hear the motivation for why we need `neo4j-harness-test`, it seems to me like the tests for the `neo4j-harness` module could reside in the test root within that module. What am I missing?

**Comment by nawroth** [comment]
@thobe Having it in the same module won't catch if some dependency that is needed in order to use `neo4j-harness` is put in the test scope. Which is what happened.

**Comment by thobe** [comment]
Could that instead be solved by having the `neo4j-harness` code actually depend on that code, so that such a mistake would be a compilation error?

**Comment by nawroth** [comment]
I think we'd have to duplicate the code then, and once we forget about updating in both places we might have the same problem again. A separate module is less brittle.

**Pull request merged**
