### PR TITLE
Remove deprecated DefaultFileSystemAbstraction

### PR DESCRIPTION
**Pull request by chrisvest**

### CODE REVIEW

**Comment by davidegrohmann** [comment]
@chrisvest needs rebase

**Comment by MishaDemianenko** [comment]
Mr @chrisvest needs another rebase

**Comment by davidegrohmann** [comment]
@chrisvest sorry but the rebase chain is getting longer...

**Comment by chrisvest** [comment]
@tinwelint @MishaDemianenko @davidegrohmann rebased

**Pull request merged**
