### PR TITLE
3.4 robust stepdown

### PR DESCRIPTION
**Pull request by andrewkerr9000**
Follow up to #11691

### CODE REVIEW

**Comment by RagnarW** [comment]
Code looks good. There does not seem to be a test, I know the issues was seen in soaks, is it not possible to reproduce in an unit test or IT?

I've never been in this part of the code so would be better to have it approved by those who have.

**Comment by andrewkerr9000** [comment]
@RagnarW I take your point about tests, but that would need to be done with @hugofirth

**Review by martinfurmanski — APPROVED** [review]
Looks correct to me. The dual paths into casLeaders is a bit of a mind-twist, but I think it will currently always eventually reach the correct end state, and the base problem is probably that we have two separate LeaderInfos stored.

**Comment by andrewkerr9000** [comment]
Failing test is unrelated

**Comment by hugofirth** [comment]
I think the reason `leaderInfo` was not an `AtomicReference` is that it is only ever written from the one thread (this one) via the `RaftTopologyConnector`. As a result, volatile is enough? 

The same _was_ true of `stepDownInfo` as well, except that we ended up needing to clear it out inside `refreshRoles`, so now that has to be wrapped :smile:. 

On balance, I can't decide whether:

a) it is a good idea to have both `leaderInfo` and `stepDownInfo` as `AtomicReference`s for consistency
b) it is better to have `stepDownInfo` as an `AtomicReference` and leave `leaderInfo` as a volatile for simplicity. This class is getting pretty hairy as it is.
c) or finally, we actually do something to clear the `stepDownInfo` on this thread. Something like a term comparison in `setLeader`? If the raft connector reports a new leader with a later term than the stored `stepdownInfo` then it is safe to clear the `stepdownInfo`. 

Thoughts @andrewkerr9000 @martinfurmanski @RagnarW 

P.S. Sorry about the delayed response.

**Comment by martinfurmanski** [comment]
@hugofirth My personal feeling is that we try to solve those issues with a larger restructuring, so that we by design can avoid this type of synchronization headache. For the issue at hand I think we should just aim at the minimal solution.

**Pull request merged**
