### PR TITLE
Core-edge: Exclude store_lock when deleting store.

### PR DESCRIPTION
**Pull request by martinfurmanski**
Store lock is not part of the store files. It has its own lifecycle.

### CODE REVIEW

**Comment by chrisvest** [comment]
@martinfurmanski How about a test that verifies that we don't delete any files not part of a store, when doing a store copy?

**Comment by martinfurmanski** [comment]
@chrisvest It would be nice to have such a component instead.

**Comment by MishaDemianenko** [comment]
@martinfurmanski it would be nice to have a test first at least

**Comment by martinfurmanski** [comment]
@MishaDemianenko You need the component to test first, that what was my comment referred to.

**Comment by lutovich** [comment]
@martinfurmanski class `StoreFiles` is enough of a component to have test for.

**Comment by martinfurmanski** [comment]
@lutovich Disagreed.

**Comment by lutovich** [comment]
@martinfurmanski class `StoreFiles` is a unit and should have a unit test. What do you disagree with?

**Comment by martinfurmanski** [comment]
@lutovich Not the right forum. Hit me up tomorrow.

**Comment by lutovich** [comment]
@martinfurmanski hit you for not writing unit test? I wish I could do it but you're into jujutsu.

**Pull request merged**
