### PR TITLE
Don't delete known_host

### PR DESCRIPTION
**Pull request by pontusmelke**
This is no longer necessary.

### CODE REVIEW

**Comment by lassewesth** [comment]
Approved @pontusmelke.

**Comment by lutovich** [comment]
@pontusmelke should the target branch be 3.1?

**Comment by pontusmelke** [comment]
@lutovich The test isn't there in 3.0 so this is as far back as it can go?

**Comment by lutovich** [comment]
@pontusmelke target branch is 3.4 right now. I'll change it to 3.1.

**Comment by pontusmelke** [comment]
@lutovich Ah sorry, my bad!

**Pull request merged**
