### PR TITLE
Unflake ClusterPartitionIT

### PR DESCRIPTION
**Pull request by tinwelint**

### CODE REVIEW

**Review by burqen — CHANGES_REQUESTED** [review]
Looking at the latest test failures in `ClusterPartitionIT` they seem to all have failed on some `RuntimeException`, e.g. `TransactionTerminatedException`.
So I don't think retry on `TransientFailureException` will help. Or am I missing something?

Otherwise I think this change looks good!

**Comment by tinwelint** [comment]
@burqen `TransactionTerminatedException` is a `TransientFailureException` no?

**Comment by burqen** [comment]
@tinwelint Not from what I can see.
Extends `TransactionFailureException` 
https://github.com/neo4j/neo4j/blob/3.1/community/graphdb-api/src/main/java/org/neo4j/graphdb/TransactionTerminatedException.java#L28
which extends `RuntimeException`
https://github.com/neo4j/neo4j/blob/3.1/community/graphdb-api/src/main/java/org/neo4j/graphdb/TransactionFailureException.java#L25

**Comment by tinwelint** [comment]
You're probably misreading the code and my comment. `TransactionFailureException` != `TransientFailureException`

**Pull request merged**
