### PR TITLE
Reduce field visibility

### PR DESCRIPTION
**Pull request by janekdb**
All tests pass locally.

### CODE REVIEW

**Comment by klaren** [comment]
Thanks for the PR. Could you rebase this on the 4.1 branch instead?

**Comment by janekdb** [comment]
Closing to target 4.1 instead following rebase. As far as I know GitHub does not offer a way to change the target branch.

**Comment by klaren** [comment]
You can press the `Edit` button on the top right, then you can change the base branch.

**Comment by janekdb** [comment]
@klaren Ah, thanks for the tip!

**Pull request closed without merging**
