### PR TITLE
Fix buf leak in encoders

### PR DESCRIPTION
**Pull request by davidegrohmann**
Do not allocate buffers by hand but ask netty to allocate them for us,
so they can do the tracking and release them when they are not needed
anymore.

### CODE REVIEW

**Review by digitalstain — APPROVED** [review]
Yup, looks good.

**Comment by lutovich** [comment]
@davidegrohmann it would also be great to run unit tests and ITs with Netty's leak detector turned on, as described here: http://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks

**Comment by davidegrohmann** [comment]
@lutovich will do in another PR

**Comment by apcj** [comment]
Superseded by https://github.com/neo4j/neo4j/pull/8284 so closing

**Pull request closed without merging**
