### PR TITLE
Temporal/spatial indexing in a single GBPTree index

### PR DESCRIPTION
**Pull request by tinwelint**
Leaving out the middle-layer multiplexing from value type/coordinate reference system --> index file. Simplifies those index implementations a great deal.

### CODE REVIEW

**Comment by tinwelint** [comment]
@OliviaYtterbrink @fickludd this is just an idea of how to simplify this layer. What do you think of an approach like this?

**Comment by fickludd** [comment]
@tinwelint 👏. This seems unreasonably much simpler. Why did you not force us to do it form the beginning? 

I can't come up with any reasonable problem with this...
 
 * Indifferent: fewer file handles in theory, probably the same in practice
 * Great: much easier code
 * Imdifferent: 4-12% bigger footprint
 * Great: less caching and synchronization and laziness
 * Nice: simpler to add additional temporals
 * Annoying: index migration

I guess it moves type branching into a much hotter position... maybe some benchmarks on a system of two different temporal indexes would shed light on if this has any measurable impact.

**Comment by tinwelint** [comment]
@fickludd If we would've paired from the beginning then we might have ended up here, you know :)

Yes, absolutely correct: type branching will be more present down in the very hot sections. We have to make sure performance doesn't degrade because of it. The only place where this could potentially be visible would be read results of size > 1, otherwise the branching would be as present, just in another (more expensive) layer. For updates and the likes this branching is 1-to-1, but should be much cheaper down there.

**Comment by tinwelint** [comment]
Replaced by #11818

**Pull request closed without merging**
