### PR TITLE
Lucene index sharding

### PR DESCRIPTION
**Pull request by MishaDemianenko**
Introduce IndexStorage as an abstraction that responsible 
for physical representation of index: folders, directories, etc.

Update lucene index to be possibly splitter into several partitions
New index folder layout will be indexId/partitionId where new partitions will be created on demand.

Label scan store will continue to use simple folder structure that do not include partitions.

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@davidegrohmann we think it's not yet ready to be merged since we do not think we have enough tests yet even for single partition case, plus me and @lutovich are officially on vacation next couple of days

**Comment by lutovich** [comment]
@davidegrohmann I thought it was ok to merge this PR but it is probably not - test coverage for new components is not sufficient.

**Comment by davidegrohmann** [comment]
@lutovich @MishaDemianenko alright then. Wondering if we could have made these changes incrementally and merge them more often.

**Comment by MishaDemianenko** [comment]
@davidegrohmann what we want to do - is to transform current functionality into single partition case and as soon as we will finish (with enough tests) we will merge it. Then will continue with multiple partition case in the following pr(s). 
Keeping first step in a single pr save us tons of time because we do not need to make sure our intermediate state keeps tests happy.

**Comment by MishaDemianenko** [comment]
@davidegrohmann, @tinwelint guys your are welcome to start review of first part of lucene index partitioning (simple scenario of single partition - current behaviour, and partitioned writers, limited ability to read data from partitions). If you will need some additional description of work done please let me know

**Comment by tinwelint** [comment]
@MishaDemianenko it's difficult to spot any particular issues. I think this looks good in general and manual testing worked fine, knowing that partitioned reader comes in a separate PR. So rebase and I'm happy to merge.

**Comment by MishaDemianenko** [comment]
@tinwelint rebased and non performance related comments addressed

**Comment by MishaDemianenko** [comment]
@tinwelint ping

**Pull request merged**
