### PR TITLE
Warnings for unavailable labels, relationship types, and properties

### PR DESCRIPTION
**Pull request by pontusmelke**
When user provides missing (or misspelled) labels, relationship types, and/or properties there is now a warning in the browser.

### CODE REVIEW

**Comment by jexp** [comment]
is this for read only queries only? b/c updating queries might create just those missing tokens (which we "could" check, but that might be overkill for this scope)

**Comment by jexp** [comment]
Super exciting!

**Comment by pontusmelke** [comment]
@jexp It is only implemented in the cost planner, so no write support until cost planner supports writes...

**Comment by jexp** [comment]
Ah cool, good to know :) Thanks a lot.

**Pull request merged**
