### PR TITLE
Run IO module tests in parallel

### PR DESCRIPTION
**Pull request by chrisvest**
Inspired by our recent discussions, @benbc

### CODE REVIEW

**Comment by benbc** [comment]
Does it run faster?

**Comment by chrisvest** [comment]
Doesn't look like it makes any useful difference on the build agents. Only helpful for local builds, apparently :(

**Comment by benbc** [comment]
Enough difference that we should consider upgrading the build agents somehow?

**Comment by chrisvest** [comment]
Locally the IO module build time goes from 2m 40s to 1m 30s or so. I don't know if that's enough. It's not very much compared to building the whole project.

**Pull request closed without merging**
