### PR TITLE
improvements for neo4j-harness

### PR DESCRIPTION
**Pull request by sarmbruster**
3 small improvements for neo4j-harness: 
- expose GraphDatabaseService in ServerControls and Neo4jRule -> enables assertions based on GDB
- enable GDB based fixtures by using Function<GraphDatbaseService,Void>
- InProcessServerBuilder and Neo4jRule use a exisiting graph.db

### CODE REVIEW

**Comment by ikwattro** [comment]
Big :+1:

**Comment by sarmbruster** [comment]
updated the PR based on a discussion with @cleishm. Instead of directly using the source store, it is copied over using `TestServerBuilder.copyFrom(File)?

**Comment by jakewins** [comment]
Looks good Stefan!

**Comment by jakewins** [comment]
Would you add a small note in the changelog of this module to the PR?

**Comment by jakewins** [comment]
@sarmbruster looks good! I've rebased this onto latest 2.3 and squashed it into one commit, will merge once this PR is green: https://github.com/neo4j/neo4j/pull/4516

**Pull request closed without merging**
