### PR TITLE
Add metrics for slave pull updates

### PR DESCRIPTION
**Pull request by davidegrohmann**
The metrics expose the number of pulled update events happened so far and the tx id used to pull updates in the last event.

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@davidegrohmann needs rebase

**Comment by davidegrohmann** [comment]
@MishaDemianenko rebased

**Comment by MishaDemianenko** [comment]
@davidegrohmann looks good, will merge on green.

**Comment by MishaDemianenko** [comment]
@davidegrohmann can you please rebase, there where another metrics related stuff that causing conflicts

**Pull request merged**
