### PR TITLE
do not block on I/O in catchup channel pool

### PR DESCRIPTION
**Pull request by martinfurmanski**
The critical sections now only span the shared data structures.

changelog: Fix deadlock in catchup pool.

### CODE REVIEW

**Comment by mneedham** [comment]
Looks good to me.

**Comment by crichey** [comment]
Would this bug had leaded to VERY long (hours) catchup periods?

**Comment by martinfurmanski** [comment]
@crichey No, this would lead to no progress whatsoever (infinite catchup periods).

I have fixed another issue which will improve catchup speed significantly: https://github.com/neo4j/neo4j/pull/9070

**Comment by crichey** [comment]
Cool. Did that make the 3.1.3 release?

**Comment by martinfurmanski** [comment]
@crichey Afraid not!

**Pull request merged**
