### PR TITLE
3.4 monitor negotiated protocols

### PR DESCRIPTION
**Pull request by andrewkerr9000**
Procedure for showing installed protocols. Only shows client connections currently.

### CODE REVIEW

**Comment by andrewkerr9000** [comment]
Test failure is unrelated.

**Review by phughk — APPROVED** [review]
Would be nice to have a unit test as well, but otherwise great!

**Comment by andrewkerr9000** [comment]
Added unit tests.

**Comment by andrewkerr9000** [comment]
I'm not sure `dbms.cluster.protocols` is a good name. Maybe something more clearly implying intracluster connections and protocols.

**Review by martinfurmanski — APPROVED** [review]
Minor offline comments, but looks good

**Pull request merged**
