### PR TITLE
Set a user-agent in http when using load csv

### PR DESCRIPTION
**Pull request by davidegrohmann**
In order to differentiate Neo load csv requests from other Java
applications, a Neo specific user-agent is set when using load csv
connections.

### CODE REVIEW

**Comment by pontusmelke** [comment]
Can't we keep new features to 3.1?

**Comment by davidegrohmann** [comment]
It is not a new feature, using the default has problematic side-effects.

**Comment by pontusmelke** [comment]
So it is a bug then? How can we be sure that no one is filtering/allowing the current user agent?

**Comment by davidegrohmann** [comment]
@pontusmelke that's actually the problem: http://www.webuseragents.com/ua/1062554/java-1-8-0_91

**Pull request merged**
