### PR TITLE
Port VarLengthAcceptance to the TCK

### PR DESCRIPTION
**Pull request by Mats-SX**
- Remove tests with only result assertions
- Remove test assertions on remaining tests
- Rename test class to clarify new purpose
- Implement new error detail `InvalidRelationshipPattern`
  - The string literals will be replaced with proper constants when the TCK gets updated

This should only be merged after https://github.com/opencypher/openCypher/pull/77 gets merged.

### CODE REVIEW

**Comment by petraselmer** [comment]
@Mats-SX : looks good, just needs a rebase and then it can be merged

**Comment by Mats-SX** [comment]
@petraselmer Rebased.

**Comment by petraselmer** [comment]
@Mats-SX : another rebase required...

**Comment by Mats-SX** [comment]
@petraselmer Rebased again.

**Pull request merged**
