### PR TITLE
Replication benchmark security

### PR DESCRIPTION
**Pull request by martinfurmanski**

### CODE REVIEW

**Review by RagnarW — COMMENTED** [review]
@OliviaYtterbrink Is there an easy way to test the security here?

**Comment by martinfurmanski** [comment]
@OliviaYtterbrink Do you agree that this is the desired security level and that it is correctly enforced?

**Comment by OliviaYtterbrink** [comment]
@martinfurmanski yes

**Comment by martinfurmanski** [comment]
@OliviaYtterbrink Thank you!

**Pull request merged**
