### PR TITLE
Treat deleted relationship in the middle of a chain as inconsistency

### PR DESCRIPTION
**Pull request by MishaDemianenko**
Enhance consistency checker to track usage flag of relationship records in chain. 
This gives possibility to check chain for presence of deleted records and treat them as inconsistencies.

### CODE REVIEW

**Comment by tinwelint** [comment]
Neat, I like it

**Comment by tinwelint** [comment]
@MishaDemianenko test failures look related

**Comment by tinwelint** [comment]
Marking not ready since it's for 3.2

**Comment by MishaDemianenko** [comment]
@tinwelint rebased, target to 3.2 and labels updated.

**Comment by MishaDemianenko** [comment]
@tinwelint ping

**Pull request merged**
