### PR TITLE
`KernelIntegrationTest` retain db on restart

### PR DESCRIPTION
**Pull request by ragadeeshu**
Some extending tests already assume this to be the case.

### CODE REVIEW

**Comment by ragadeeshu** [comment]
@MishaDemianenko Updated :)

**Comment by MishaDemianenko** [comment]
@ragadeeshu everything looks fine except removed test, can you please explain why that gets removed?

**Comment by ragadeeshu** [comment]
@MishaDemianenko Because it tests for old behavior, that was changed in https://github.com/neo4j/neo4j/pull/9068 This test should have been removed back then.

**Review by MishaDemianenko — APPROVED** [review]
Ok, thx. LGTM

**Pull request merged**
