### PR TITLE
Created a Powershell Module to manage a Neo4j Server

### PR DESCRIPTION
**Pull request by glennsarti**
Completed the help text for all functions
Fixed typo in Install-Neo4jArbiter
Changed Wait property to only be valid for console servers for Start-Neo4jServer and Start-Neo4jArbiter

### CODE REVIEW

**Comment by glennsarti** [comment]
Can I get someone to please kick off another build of this PR.  The last one failed due to github issue but I can't run it again.

**Comment by lutovich** [comment]
@glennsarti done, build is running

**Comment by glennsarti** [comment]
Thankyou @lutovich

**Comment by glennsarti** [comment]
@benbc PR is ready for merge now.

**Comment by glennsarti** [comment]
@benbc Completed all of the remaining unit tests and fixed some bugs

**Comment by lassewesth** [comment]
@glennsarti At a glance this looks good! I'll get Pester working, then merge. Ta for the good work.

**Pull request merged**
