### PR TITLE
Fix minor issues with assertEventually.

### PR DESCRIPTION
**Pull request by martinfurmanski**

### CODE REVIEW

**Comment by martinfurmanski** [comment]
All checks have failed for unrelated issues. Please merge.

**Comment by benbc** [comment]
@martinfurmanski I agree that we should not ignore the interrupt, but I disagree with the way you're handling it. I think we should treat it the same way as a timeout -- fail if the condition still doesn't hold.

**Comment by martinfurmanski** [comment]
@benbc I don't agree. Interrupts are for interrupt handlers. InterruptExceptions will fail tests.

**Comment by benbc** [comment]
@martinfurmanski I don't think you are respecting the intended semantics of Java interrupts. But I don't think in this case it's important enough to hold up this PR while I try to persuade you.

**Comment by martinfurmanski** [comment]
@benbc I think I am, but I would be happy to learn otherwise.

**Comment by martinfurmanski** [comment]
@maxsumrall Do you wish to take a look? It's not urgent in any way.

**Comment by MishaDemianenko** [comment]
@martinfurmanski Why did you merge it yourself and not wait for a reviewer?

**Comment by martinfurmanski** [comment]
@MishaDemianenko It had plenty of reviews

**Pull request merged**
