### PR TITLE
Delete obsolete tests that never run in CI

### PR DESCRIPTION
**Pull request by davidegrohmann**
The tests are run only when they have > 1GB of heap.  This condition
is never met since ITs in kernel module are run with 300MB heap limit.

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
Part of this test was executed: `makeSureCantCreateNodeWithMagicNumber` is actually valid test

**Comment by davidegrohmann** [comment]
@MishaDemianenko good catch, I am gonna relocate that test somewhere else

**Review by chrisvest — APPROVED** [review]
Looks good. Can merge on green build.

**Comment by chrisvest** [comment]
@davidegrohmann The `BatchInserterTest` actually failed due to a file lock issue, which I think might be caused by the test you added taking and not releasing a Lucene file lock:

```
[08:38:50]Running org.neo4j.index.impl.lucene.legacy.BatchInsertionIT
[08:38:52]Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.649 sec <<< FAILURE! - in org.neo4j.index.impl.lucene.legacy.BatchInsertionIT
[08:38:52]shouldBeAbleToMakeRepeatedCallsToSetNodeProperty(org.neo4j.index.impl.lucene.legacy.BatchInsertionIT)  Time elapsed: 0.105 sec  <<< ERROR!
[08:38:52]org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.api.impl.labelscan.LuceneLabelScanStore@5add1ce2' failed to initialize. Please see attached cause exception.
[08:38:52]  at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:127)
[08:38:52]  at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
[08:38:52]  at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
[08:38:52]  at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:94)
[08:38:52]  at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:776)
[08:38:52]  at org.neo4j.kernel.api.impl.index.partition.WritableIndexPartition.<init>(WritableIndexPartition.java:48)
[08:38:52]  at org.neo4j.kernel.api.impl.index.partition.WritableIndexPartitionFactory.createPartition(WritableIndexPartitionFactory.java:45)
[08:38:52]  at org.neo4j.kernel.api.impl.index.AbstractLuceneIndex.open(AbstractLuceneIndex.java:98)
[08:38:52]  at org.neo4j.kernel.api.impl.index.WritableAbstractDatabaseIndex.open(WritableAbstractDatabaseIndex.java:64)
[08:38:52]  at org.neo4j.kernel.api.impl.labelscan.LuceneLabelScanStore.init(LuceneLabelScanStore.java:159)
[08:38:52]  at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:405)
[08:38:52]  at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:426)
[08:38:52]  at org.neo4j.kernel.lifecycle.LifeSupport.bringToState(LifeSupport.java:315)
[08:38:52]  at org.neo4j.kernel.lifecycle.LifeSupport.add(LifeSupport.java:248)
[08:38:52]  at org.neo4j.unsafe.batchinsert.internal.BatchInserterImpl.<init>(BatchInserterImpl.java:295)
[08:38:52]  at org.neo4j.unsafe.batchinsert.BatchInserters.inserter(BatchInserters.java:83)
[08:38:52]  at org.neo4j.unsafe.batchinsert.BatchInserters.inserter(BatchInserters.java:66)
[08:38:52]  at org.neo4j.unsafe.batchinsert.BatchInserters.inserter(BatchInserters.java:48)
[08:38:52]  at org.neo4j.index.impl.lucene.legacy.BatchInsertionIT.shouldBeAbleToMakeRepeatedCallsToSetNodeProperty(BatchInsertionIT.java:108)
```

**Comment by davidegrohmann** [comment]
@chrisvest test fixed

**Pull request merged**
