### PR TITLE
Removed option to find path with exact depth from ShortestPath

### PR DESCRIPTION
**Pull request by burqen**
It does not make sense to find a shortest path with specified length and ExactDepthPathFinder already provides that functionality.

Tests for both ExactDepthPathFinder and ShortestPath runs.

### CODE REVIEW

**Comment by jakewins** [comment]
Ugh, sorry CI is not public. It's failing with two related-looking tests:

    java.lang.AssertionError: These were expected, but not found: [a,c,g,k]
      at org.junit.Assert.fail(Assert.java:88)
      at org.junit.Assert.assertTrue(Assert.java:41)
      at common.Neo4jAlgoTestCase.assertPaths(Neo4jAlgoTestCase.java:180)
      at org.neo4j.graphalgo.path.TestShortestPath.testExactDepthFinder(TestShortestPath.java:203)

    java.lang.AssertionError: These unexpected paths were found: [a,b,c,b,d,c,e]. In addition these expected paths weren't found:[]
      at org.junit.Assert.fail(Assert.java:88)
      at org.junit.Assert.assertTrue(Assert.java:41)
      at common.Neo4jAlgoTestCase.assertPaths(Neo4jAlgoTestCase.java:179)
      at org.neo4j.graphalgo.path.TestShortestPath.testExactDepthPathsReturnsNoLoops(TestShortestPath.java:253)

**Comment by jakewins** [comment]
Also ping @tinwelint, care to review?

**Comment by tinwelint** [comment]
I like this change, although I don't know how well `ExactDepthPathFinder` works as it hasn't been "officially" exposed from `GraphAlgoFactory` before and it seems to have a way to avoid dense nodes and things like that. Unit tests seems to be very few around it as well. I would like to see some more tests added as well as perhaps a rough performance comparison between the two, perhaps a comparison between `ShortestPath` w/ the paths-with-length functionality compared to `ExactDepthPathFinder`

**Comment by burqen** [comment]
Existing testing seems to be working now. I will extend the testing of ExactDepthPathFinder further.

**Comment by burqen** [comment]
New Pull Request superseded by
#4564 

Closing this one.

**Pull request closed without merging**
