### PR TITLE
Remove the maven git plugin, and instead get the git description, branch and abbreviated commit SHA through environment variables

### PR DESCRIPTION
**Pull request by chrisvest**

### CODE REVIEW

**Comment by benbc** [comment]
A great improvement. What is the "describe" actually used for?

**Comment by chrisvest** [comment]
@benbc It's used in the commit description property in the component version template: https://github.com/neo4j/neo4j/pull/6072/files#diff-600376dffeb79835ede4a0b285078036L104

**Comment by chrisvest** [comment]
@benbc Better link: https://github.com/chrisvest/neo4j/blob/2.2-upgrade-git-plugin/pom.xml#L107

**Comment by benbc** [comment]
I really don't think that does what the person who wrote it thinks it does. This is from the help text of `git describe`:

> The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit.

So:

```
[ben:~/src/neo4j/neo4j] > git status
On branch 2.3
Your branch is up-to-date with 'upstream/2.3'.

nothing to commit, working directory clean
[ben:~/src/neo4j/neo4j] > git describe
2.3.1-124-g15da4c5
```

I can't for the life of me see how that is useful.

**Comment by chrisvest** [comment]
@thobe Do you think we can remove the `git describe` part? Can we remove the `ComponentVersion.getCommitDescription()` method?

**Comment by thobe** [comment]
@chrisvest it is only used for identifying a build that contained uncommitted code, so that we can identify unsupported builds. I don't think users build from source as much anymore, so this it is probably ok to remove.

**Comment by chrisvest** [comment]
@thobe With the system I've laid out here, those people would get an "unkown-commit" where there would normally be a commit SHA (unless they provide a `GIT_COMMIT` environment variable) so that case would be covered as well. So yeah, let's remove the commit description.

**Pull request merged**
