### PR TITLE
specialising functional interfaces.

### PR DESCRIPTION
**Pull request by ameyaKetkar**
Hello,
I am a grad student attempting to write a tool for type migration in Java. I was testing it upon specialising functional interfaces. I found these cases in the project.
This project was an excellent dataset for testing, thanks for all your work. :)

### CODE REVIEW

**Comment by klaren** [comment]
Hi,

In order for us to accept your code you have to sign our CLA: https://neo4j.com/developer/cla/

There are also several merge conflicts, to solve those please rebase your changes on the latest 3.4 branch.

Thanks for your contribution!

**Comment by klaren** [comment]
@ameyaKetkar any news?

**Comment by ameyaKetkar** [comment]
@klaren Sorry for the delay. I was travelling home for the spring break, so could not do this . :\

**Comment by ameyaKetkar** [comment]
@klaren I rebased it, but something seems wrong. Now there are more 1500 files changed, did i make a mistake somewhere?  
P.S.  I am still learning git.

**Comment by klaren** [comment]
@ameyaKetkar Maybe you based your changes on another branch than `3.4`? That could explain the large changeset.

It might be easier to check out a clean version of the branch, re-run your tool and force push. E.g.
```
git checkout feature/specialisingFunctionalInterfaces
git fetch neo4j
git reset --hard neo4j/3.4
<run your tool>
git commit -am "specialising functional interfaces."
git push --force
```
assuming you have our repository setup as `neo4j`.
(`git remote add neo4j git@github.com:neo4j/neo4j.git`)

Also, I'm still missing a singled CLA from you, please follow the instructions at https://neo4j.com/developer/cla/ . Or if you've already done this let me know and I'll have to check again :)

**Comment by klaren** [comment]
Since 3.4 is released you have to retarget the PR for 3.5.

I will close this one and you can open a new PR based on 3.5.

**Comment by ameyaKetkar** [comment]
Thank you.

I will do it soon. 


Ameya

**Pull request closed without merging**
