### PR TITLE
fix: fixed PrimitiveLongIntKeyValueArray incorrect constructor

### PR DESCRIPTION
**Pull request by BrokenWingsIcarus**
see #12916

### CODE REVIEW

**Comment by mnd999** [comment]
Hello and thank you for the PR!

In order for us to accept it, you have to sign our CLA, more information is here: https://neo4j.com/developer/cla/

This applies to all authors of the commits. Thanks.

**Comment by BrokenWingsIcarus** [comment]
> Hello and thank you for the PR!
> 
> In order for us to accept it, you have to sign our CLA, more information is here: https://neo4j.com/developer/cla/
> 
> This applies to all authors of the commits. Thanks.

I signed it and emailed it to email address.

**Comment by BrokenWingsIcarus** [comment]
The email has not been approved. Do I need to do anything else.

**Comment by mnd999** [comment]
Things are a little slow at the moment due to summer vacations. I'll see if I can hurry it up.

**Comment by gjmwoods** [comment]
Hi @BrokenWingsIcarus. Many thanks for your PR and apologies for the delay in getting back to you.

Changes look great. We've merge your commit in the private mirror of this repo and you should see it when the two are next synched (on the next patch I believe `4.4.12`) so I will close down this PR.

Many thanks again for your contribution 🙇

**Pull request closed without merging**
