### PR TITLE
Update test cluster with setting for logs directory.

### PR DESCRIPTION
**Pull request by martinfurmanski**

### CODE REVIEW

**Comment by lutovich** [comment]
Imo there is an issue with `logs` directory placement. Commit https://github.com/neo4j/neo4j/commit/a43bc66028d479f2dcd00ea967fbcbb8aabbac77 made `logs/debug.log` independent of `storeDir` which seems strange.
So maybe it does not make sense to fix only core-edge tests?

**Comment by martinfurmanski** [comment]
@lutovich I agree but we need this in the mean time!

**Comment by MishaDemianenko** [comment]
@martinfurmanski this is a workaround for a problem, which i agree really annoying, but would updating git ignore file works better as a temporal solution?
And you will not touch actual code in anyway using that mechanism.
WDYT?

**Comment by martinfurmanski** [comment]
@MishaDemianenko That is not the issue I am solving. I am placing the files in a sane location, git has nothing to do with it, even though that of course also is annoying!

**Comment by MishaDemianenko** [comment]
@martinfurmanski That should be done for whole product/all editions/modules not only cluster setup, so you do not solving product problem

**Comment by martinfurmanski** [comment]
@MishaDemianenko Yes

**Pull request merged**
