### PR TITLE
New TCK error requiring that a relationship be directed

### PR DESCRIPTION
**Pull request by petraselmer**

### CODE REVIEW

**Comment by petraselmer** [comment]
Only merge this PR once https://github.com/opencypher/openCypher/pull/58 has been merged

**Comment by Mats-SX** [comment]
@petraselmer It has now been merged.

**Comment by petraselmer** [comment]
Can only be merged after https://github.com/neo4j/neo4j/pull/7110 has been merged

**Comment by petraselmer** [comment]
Creating a new PR to replace this one

**Pull request closed without merging**
