### PR TITLE
Use timeout()  to prevent 'apply() already in progress' error by browser

### PR DESCRIPTION
**Pull request by vimalaad**
sometimes when click on editor, browser shows a 'apply already in progress error'
please add timeout to clear this
@oskarhane 
#bug
#browser

### CODE REVIEW

**Comment by oskarhane** [comment]
Thanks @vimalaad. Should the second commit (single node view) be a part of this pr?

**Comment by vimalaad** [comment]
@oskarhane
no, pls apply the first one.
thanks

**Comment by oskarhane** [comment]
@vimalaad Since this PR has commits that shouldn't be merged I'm closing it.
However, would it be ok if I include your fix in one of my upcoming PR:s?
I can put a credit note to your github user in the commit message if you want.

**Comment by vimalaad** [comment]
thank's
it's good

**Pull request closed without merging**
