### PR TITLE
Prevent logging to stdout except via log framework

### PR DESCRIPTION
**Pull request by cleishm**
I'm quite confident in the change, and have tested by hand. If someone would also like to contribute an automated test, that would be great.

### CODE REVIEW

**Comment by jakewins** [comment]
Uhm, strongly disagree with disabling system.out for the entire process, that's just hiding the problem.

-1 on this. I'd rather we figure out how to make `InternalLoggerFactory` not log debug statements on startup - I would assume this is done by bundling some appropriate logging config file on the classpath.

**Comment by cleishm** [comment]
It's not hiding the problem: nothing should be logging via stdout anyway. There is the option to set it back again after the initialization, which is the only possible workaround for this issue. I chose not to do that, because I couldn't think of any good reason to do so.

**Comment by cleishm** [comment]
Re-opening against the correct branch

**Comment by cleishm** [comment]
BTW - closing stdout after setting up a log is standard practice in most servers, so this actually aligns with that objective (the only drawback being that we currently must still send the log output to stdout rather than directly to a file - something we can and should change in 3.0).

**Comment by jakewins** [comment]
This is not closing the actual process stdout, as I'm sure you know. This is losing the reference to the file handle. If we were closing stdout, that'd be more helpful since that would cause attempts to write to it to fail - which exactly highlights why this PR is the wrong thing to do, because it hides components erroneously writing to stdout.

Slf4j is a standard component, there is a standard way for how to bridge it's output into a log framework, and it definitely is not to drop the reference to stdout. So, we either drop a bridge in for Logback, since we already have logback in place, or we add a custom `StaticLoggerBinder` bridging into our framework.

**Comment by cleishm** [comment]
Actually, standard practice is not just to close the underlying file-handle, but to re-open it connected to `/dev/null`. This change is fairly equivalent, except that it'll work across platforms. Closing the original filehandle is definitely a great idea also, which we can do in 3.0.

If you'd like to play with logging configuration, then more than happy if you want to provide an alternative fix, for the team to compare. I felt this is the most expedient and aligns well with what standard practice in servers is anyway.

**Pull request closed without merging**
