### PR TITLE
Better error message when deleting a node with relationships.

### LINKED ISSUE #1903: delete transaction failed
Ran on localhost:7474/browser/:
MATCH (a:Person) DELETE a;

Got back:
 javax.transaction.HeuristicRollbackException: Failed to commit transaction Transaction(558, owner:"qtp1924047713-4015")[STATUS_NO_TRANSACTION,Resources=1], transaction rolled back ---> javax.transaction.xa.XAException

### PR DESCRIPTION
**Pull request by jakewins**
It took.. a while. But here is a better error message whenever a node
with relationships gets deleted.

Resolves #1903

### CODE REVIEW

**Comment by chrisvest** [comment]
@jakewins There are a number of tests that expect different exceptions in this case. Those tests need to be modified to match the new behaviour.

**Comment by davidegrohmann** [comment]
@jakewins needs rebase as well

**Comment by jakewins** [comment]
@davidegrohmann rebased!

**Comment by davidegrohmann** [comment]
@jakewins the build got stuck in `org.neo4j.kernel.impl.core.NodeTest`

**Comment by tinwelint** [comment]
@jakewins Does this also affect #117 ?

**Comment by jakewins** [comment]
Hmm, looks like it, yeah.

**Comment by davidegrohmann** [comment]
@jakewins ping

**Pull request merged**
