### PR TITLE
Allow for plugable commands in neo4j-admin in Powershell

### PR DESCRIPTION
**Pull request by glennsarti**
This pull request is the powershell equivalent for Pull Request https://github.com/neo4j/neo4j/pull/7507.  The `neo4j-admin.bat` invocation will now call the new admin tool java classes and redundant functions have been removed.  Unit tests have been updated for the new code paths.

This PR also brings parity to the environment variables set in `neo4j-shared.sh` and removes some hidden white in many of the test files.

### CODE REVIEW

**Comment by glennsarti** [comment]
@benbc for review.

**Comment by benbc** [comment]
@glennsarti This looks great. Thanks.

**Comment by benbc** [comment]
@glennsarti I have rebased this branch and force-pushed it.

**Comment by glennsarti** [comment]
Hrmm the Linux failures do not appear to be related to this PR.

**Comment by glennsarti** [comment]
Rebased this onto 3.1 at commit 1c809b18e227

**Comment by glennsarti** [comment]
I built a snapshot of 3.1 and tested on a vanilla 2012R2 server

``` batch

C:\Source\neo4j-community\bin>set NEO4J_HOME
Environment variable NEO4J_HOME not defined

C:\Source\neo4j-community\bin>neo4j-admin users list
neo4j

C:\Source\neo4j-community\bin>set NEO4J_HOME
Environment variable NEO4J_HOME not defined

C:\Source\neo4j-community\bin>set NEO4J_HOME=c:\source\neo4j-community

C:\Source\neo4j-community\bin>neo4j-admin users list
neo4j

C:\Source\neo4j-community\bin>set NEO4J_HOME
NEO4J_HOME=c:\source\neo4j-community

C:\Source\neo4j-community\bin>
```

neo4j-admin works with or without an explicit NEO4J_HOME env var.

I then manually edited out the statement:

``` powershell
  # if ( (Get-Neo4jEnv 'NEO4J_HOME') -eq $null) { Set-Neo4jEnv "NEO4J_HOME" $Neo4jHome }
```

This would stop the process level env var being created.

and received this error as expected with no NEO4J_HOME set;

``` batch

C:\Source\neo4j-community\bin>neo4j-admin users list
Exception in thread "main" java.lang.NullPointerException
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.neo4j.commandline.admin.AdminTool.main(AdminTool.java:34)

C:\Source\neo4j-community\bin>
```

**Comment by benbc** [comment]
Thanks @glennsarti. More problems with the build. I'll get this green and then merge it.

**Comment by glennsarti** [comment]
I've enabled edits from maintainers so you can push commits to my branch if needs be.

**Pull request merged**
