### PR TITLE
Adding the config variable ness for AWS ELB

### PR DESCRIPTION
**Pull request by jrgleason**
See https://support.neo4j.com/hc/en-us/requests/3019

### CODE REVIEW

**Comment by jrgleason** [comment]
See https://github.com/neo4j/neo4j/issues/6106

**Comment by spacecowboy** [comment]
Thanks for the PR @jrgleason 

Before we can merge you need to sign the `Contributor License Agreement`. It's as easy as sending an e-mail. See http://neo4j.com/developer/cla/ for further information.

Additional information on contributing code is found at
http://neo4j.com/developer/contributing-code/

**Comment by jrgleason** [comment]
Sorry missed that email sent thanks!

**Comment by benbc** [comment]
Hi @jrgleason. Could you please put the new entry at the bottom of the file rather than in the middle of the other HA stuff? And please separate with just one blank line. Thanks.

-Ben

**Comment by benbc** [comment]
@jrgleason I've implemented this myself in #6390. Thanks for prompting us to do this.

**Pull request closed without merging**
