### PR TITLE
Move the central pieces of the IR to IR module

### PR DESCRIPTION
**Pull request by Mats-SX**
`PlannerQuery`, `QueryGraph`, and lots of entangled classes.

Replaces #8719

### CODE REVIEW

**Comment by Mats-SX** [comment]
Do not merge before #8706

**Comment by Mats-SX** [comment]
Do not merge before #8774

**Comment by thobe** [comment]
#8706 and #8774 are both merged. @Mats-SX are you going to give this some love and get it to a mergeable state?

**Comment by Mats-SX** [comment]
@thobe Yes! I have a half-done rebase locally, will push ASAP.

**Comment by Mats-SX** [comment]
@thobe It is now mergeable.

**Pull request merged**
