### PR TITLE
Update incorrect and duplicated artifact names.

### PR DESCRIPTION
**Pull request by MishaDemianenko**
Update name for legacy consistency checker and neo4j-functions module.

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@nawroth can you please take a look

**Comment by nawroth** [comment]
@MishaDemianenko How about fixing this in 2.3?

**Comment by MishaDemianenko** [comment]
@nawroth was thinking is already to late since 2.3 already went into public, just to keep same naming in already leaked 2.3.x

**Comment by MishaDemianenko** [comment]
@nawroth or if you think it's fine to do so will reopen it agains 2.3?

**Comment by nawroth** [comment]
@MishaDemianenko The name shows up in builds and when searching for artifacts, but doesn't really change anything technically. I'd go for fixing it in 2.3 as there will still be many builds done for the 2.3 series.

**Comment by MishaDemianenko** [comment]
@nawroth that's correct, was just not sure how strict we are regarding changing that in the same dot version. Will retarget PR. thx

**Pull request closed without merging**
