### PR TITLE
This is important, since the text of the message directs the user to do the wrong thing

### PR DESCRIPTION
**Pull request by Alan-R**
You can see others have commented on this - even though you closed the issue.

There is a typo in the commit message - it should have said #9992.

### CODE REVIEW

**Comment by Alan-R** [comment]
Given that it just adds an 's' to a message, it's hard to see how the checks should all fail. Looks like a broken build system. Since I can't see what's wrong, I can't figure out if there is some kind of real problem (but I seriously doubt it).

**Comment by chrisvest** [comment]
It's not a build system problem. The first thing the build does, is check that all committers are connected to contributor license agreements, and apparently this check fails.

**Comment by craigtaverner** [comment]
We should rather merge the original PR at https://github.com/neo4j/neo4j/pull/10522, and that user has signed the CLA (although is not yet on the whitelist).

**Comment by Alan-R** [comment]
I thought I had signed it before, but just in case I hadn't -- I sent the CLA to cla@neotechnology, and CCed @jexp for good measure.

**Comment by sherfert** [comment]
Hi @Alan-R . It took as while, but now you are finally on our whitelist. I apologize for talking so so long to do that.

Unfortunately, your PR will need to be rebased for the CI checks to become green. We have changed our licence headers since then...

**Comment by sherfert** [comment]
Since #10522 was merged, I am closing this PR.

**Pull request closed without merging**
