### PR TITLE
browser guide updates: start, northwind, query templates

### PR DESCRIPTION
**Pull request by akollegger**
- start replaces welcome guide
- northwind added as RDBMS to graph example
- query templates provided for ad-lib query generation

### CODE REVIEW

**Comment by mneedham** [comment]
Have only skimmed so far but it looks good. One thing - we've been using lowercase first letter in property names in other places so it'd be good to keep that consistent.

e.g. CategoryName would be categoryName and so on.

WDYT?

**Comment by akollegger** [comment]
Yeah, I thought about that and couldn't decide between cluttering up the queries with re-naming versus just using the header fields. Oh, wait. I'm not smart: perhaps I shall just update the CSV.

**Comment by jexp** [comment]
I think it would make sense to put a tiny sample of the csv files to be imported in too, so that you don't fly blind in terms of column names and data values

**Comment by akollegger** [comment]
@jexp That's the kind of expanded detail which I'd hope to have on the website. The built-in content should be as lean as possible, while being useful. Let's iterate on that.

**Pull request merged**
