### PR TITLE
Deprecate CREATE nodes from parameter list of maps

### PR DESCRIPTION
**Pull request by Mats-SX**

### CODE REVIEW

**Comment by nawroth** [comment]
@Mats-SX I'd suggest a new example is created using the `UNWIND` way, and put before the old deprecated example.

**Comment by pontusmelke** [comment]
@Mats-SX @nawroth Can't we just remove the old example from the manual. I don't see the point in spelling out _the wrong way_.

**Comment by nawroth** [comment]
It does give people an additional chance to see the deprecation.
Just have to make sure the good way comes first!

**Comment by Mats-SX** [comment]
@pontusmelke It's not the wrong way in 2.3?

**Pull request merged**
