### PR TITLE
Do not plan expansion for already solved pattern relationships

### PR DESCRIPTION
**Pull request by davidegrohmann**

### CODE REVIEW

**Comment by systay** [comment]
Not sure I follow the test you are missing, @boggle. Could you write it out as a query?

**Comment by boggle** [comment]
I was thinking about something like M a-r1-b, c-r2-d WITH * LIMIT 1 M a-r1-b, c-r2-d, a-r3-d. The point being that in the 2nd QG we'd get leave plans that solve 2 pattern relationships already and thus should be in the right spot in the table.  Might also influence how we pick k and where we start iterating in the inner loop.  Does this make sense?

**Comment by davidegrohmann** [comment]
@boggle yes I have written one and it does not work yet as expected. On the other hand, it wasn't working even before these changes. So I don't think that should be part of this PR.

**Comment by boggle** [comment]
Closing for now; @craigtaverner and me are bringing it in as part of our IDP work.

**Comment by boggle** [comment]
Actually merging now and building a top.

**Pull request merged**
