### PR TITLE
Provide more detailed error messages when ordering by mixed types

### PR DESCRIPTION
**Pull request by thobe**
Also for when aggregating with MIN or MAX on mixed types, or when ordering by list values.

### CODE REVIEW

**Comment by Mats-SX** [comment]
According to the [orderability CIP](https://github.com/opencypher/openCypher/blob/master/cip/1.accepted/CIP2016-06-14-Define-comparability-and-equality-as-well-as-orderability-and-equivalence.adoc#331-orderability), ordering between types should not be an error. Ordering should be defined across any set of values. I think that instead of curating these error messages, we should adapt behaviour so that no errors are thrown at all.

Related: #8745

**Comment by thobe** [comment]
@Mats-SX while that is true for _new_ versions of Cypher, I don't think we should be changing the behaviour of old versions. What we _should_ do though, is make sure that the error messages our users are faced with are as helpful as they can be.

**Comment by thobe** [comment]
Build failure is due to the docs build not covering `2.3`.

**Comment by thobe** [comment]
@Mats-SX Your observation is very much relevant for the forward-merging process of this pull request though, so thank you for noting it.

**Pull request merged**
