### PR TITLE
Mention that import-tool can handle compressed archives

### PR DESCRIPTION
**Pull request by mneedham**

### CODE REVIEW

**Comment by mneedham** [comment]
@chrisvest  do you think this would be sufficient?

**Comment by chrisvest** [comment]
@mneedham You can't have more than one file per archive. So for instance it only turns `--nodes nodes.csv` into `--nodes nodes.csv.gz` and likewise for relationships.

**Comment by mneedham** [comment]
@chrisvest ok I'll refactor that sentence

**Comment by mneedham** [comment]
@chrisvest how about this?

**Comment by chrisvest** [comment]
@mneedham :+1:

**Pull request merged**
