### PR TITLE
Remove auto indexing docs

### PR DESCRIPTION
**Pull request by davidegrohmann**

### CODE REVIEW

**Comment by davidegrohmann** [comment]
@nawroth can you please have a look?

**Comment by nawroth** [comment]
Shouldn't `AutoIndexer` and `RelationshipAutoIndexer` (and some related stuff) be deprecated?

**Comment by davidegrohmann** [comment]
@nawroth you are right I am doing it right now

**Comment by davidegrohmann** [comment]
@tinwelint I have added an explanation for the deprecation
@nawroth can you please check if the wording needs any improvement?

**Pull request merged**
