### PR TITLE
Updates the Installer.bat to allow multiple instances and spaces in wind...

### PR DESCRIPTION
**Pull request by cskardon**
This allows a Windows user to install neo4j in a directory with spaces (see Issue #1900) and also allows multiple instances to be installed on a single machine (see Issue #4432).

If you run `Neo4jInstaller.bat install` it will behave as per normal, installing a service with the name `Neo4j-Server`, and display name `Neo4j Graph Database`.

There are now two extra arguments, used like this:

```
Neo4jInstaller.bat install Service-Name Service-Display-Name
```

So, running:

```
Neo4jInstaller.bat install neo4j-project-name "Neo4j for Project Name"
```

Will install to the Windows Services with a service name of `neo4j-project-name` and display name of `Neo4j for Project Name`.

If you attempt to put a space into the service name, the usage will be displayed and it will gracefully exit.

### CODE REVIEW

**Comment by glennsarti** [comment]
I tried various combinations and the new code worked great.  I don't have access to the CI system so I can't help you with fixing the build issue.  @jexp are you able to assist here?

**Comment by cskardon** [comment]
Would be nice if the CI system mentioned _why_ it was failing, unless I've missed a way to test .bat files... :)

**Comment by glennsarti** [comment]
In my experience with TC, an Error Code 1 from batch file is just a generic error code.  I've reached out to @jexp again for assistance.

In the mean time,your comment has raised an interesting point.  Can we unit test these scripts? I don't know of anything to test batch files. However you can use Pester for Powershell.

Another point, is there a way to know which Windows Service is being used for which Neo4j Installation. e.g.

```
C:\Neo\neo4j-install\bin\Neo4jInstaller install neoservice-prod
D:\Neo\neo4j-install\bin\Neo4jInstaller install neoservice-test
```

When you look at the neo installation `C:\Neo\neo4j-install` how would you know the appropriate windows service name? Now I know you could just search through all of the windows services and parse the ImageName, but that seems wasteful. Does that seem like something neo4j users would need to know? If so, where could we store that information? Perhaps modifying the `neo4j-wrapper.conf` file?

**Comment by cskardon** [comment]
There's no way I know of to unit test bat files, a project did start ~ 2011 but the last check in for that was 2012, so stale for a good 3 years.

You can tell which instance is running what via the services dialog, I guess ideally you'd see if you can get the installed location from the `sc` command (to add services).

Name wise I don't know how you'd get the service name from the install location. `sc` doesn't seem to provide this functionality. It would be nice to have something like `sc query "c:\<location>"` and for it to return `neoservice-test`. 

There might be a way, I'll have a look as it would be nice to add some extra niceness rather than having to know the name - saying that - installing a db isn't something that's done _that_ frequently, so probably not urgent at the moment.

**Comment by jotomo** [comment]
@cskardon The CI is configured to only run builds for users on a whitelist. Unless someone from the Neo folks adds you to it, the CI will abort the build with the less than helpful "Exit code 1" error.

**Comment by glennsarti** [comment]
@jotomo @cskardon should already be done as he's on the CLA list.  Unless there's yet another list?

**Comment by chrisvest** [comment]
Updating the CI whitelist is still a manual process for us. I've updated it and rerun the build, so it's green now.

**Comment by chrisvest** [comment]
@cskardon Looks like you need to rebase your changes and fix some conflicts.

**Comment by zhenlineo** [comment]
The change looks good to me.

**Comment by benbc** [comment]
@akollegger Do you have a view on adding this functionality?

**Comment by akollegger** [comment]
@benbc I offered a monologue on slack while you were away. The summary is: this looks great and will be a lovely convenience for Windows users. 

Assuming we have some way of testing the multi-service install. I don't see that here, and can't guess what that would look like on Windows. Any ideas @glennsarti or @cskardon ?

**Comment by glennsarti** [comment]
@akollegger @benbc @cskardon To do a multi-service install;
- Each Neo Service would have it's own installation of Neo e.g. `C:\Program Files\Neo4j Server1`, `C:\Program Files\Neo4j Server2` etc.
- Each Neo Service would have it's own unique Windows Service Name e.g. `Neo-4jServer1`.`Neo4j-Server2` etc.
- You would probably want to limit the memory consumption per instance

Using this PR, I would no longer have to edit the Neo4jInstaller.BAT file manually to put in the unique names. Instead it's just a tweak to a script.

I use this technique already when creating a 3 node cluster instance to test some configuration settings.  I just realised another PR would need to be raised to modify the Neo4j-Arbiter service as the installer shoud have the same functionality too.

As stated before, there's currently no way to unit test the batch files.  Does the Neo4j build process currently test multiservice installs for a *nix platform?

**Comment by benbc** [comment]
@akollegger, @glennsarti This will need testing manually.

**Comment by digitalstain** [comment]
I will echo @benbc and point out that this PR was merged after i manually tested it and concluded that previous behaviour remains (with spaces in paths not being a problem anymore, of course) and the new behaviour works as expected. I do not see how we could effectively test this in an automated way - suggestions more than welcome.

**Comment by cskardon** [comment]
@akollegger @benbc @glennsarti 
The only thing I could think of doing would be switching to a PowerShell script instead - you could unit test it, but obviously that's pretty much an entire re-write. 

PS would allow you to be able to work out which instance you were querying when you do a `remove`, `status` etc

```
$pathWildSearch = split-path -parent $MyInvocation.MyCommand.Definition
$pathWildSearch = $pathWildSearch -replace "\\", "\\"
gwmi -Query "select * from win32_service where pathname like '%$pathWildSearch%' and state='Running'" | Format-Table -Property Name, State, PathName -AutoSize -Wrap
```

Which would stop you needing to supply the 'name' argument for `status` and `remove` switches.

**Pull request merged**
