### PR TITLE
Update JLine 0.9.94 to JLine 2.12.

### PR DESCRIPTION
**Pull request by boyvanduuren**
This commit updates the JLine library to the latest version. This fixes a few current
issues with the shell (delete now actually does delete instead of backspace, for instance).

### CODE REVIEW

**Comment by boyvanduuren** [comment]
There are still references to jline-0.9.94 in other files, I wasn't quite sure whether I needed to change these in this pull request as well. If so, please let me know.

**Comment by jakewins** [comment]
@boyvanduuren hey! Sorry for the late follow-up :( For legal reasons, would you mind signing our contributor agreement? It's a 2-min email, and then you'll be listed as a contributor for future contributions.

Details here: http://neo4j.com/docs/milestone/cla.html

**Comment by boyvanduuren** [comment]
@jakewins np. I sent a mail agreeing to the CLA before I did the commit, so that should be in order :)

**Comment by jakewins** [comment]
Rebased and merged here; https://github.com/neo4j/neo4j/commit/87d9e037d9ccd518fbb59c53ef0aebab1cdd93be

**Pull request closed without merging**
