### PR TITLE
More consice logging about log rotation, pruning and checkpointing

### PR DESCRIPTION
**Pull request by tinwelint**
Previously the logging regarding log rotation pruning and checkpoint was very
verbose w/o actually including much information, e.g check pointing was logged like this:

```
2017-10-03 17:56:19.589+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [30731131]:  Starting check pointing...
2017-10-03 17:56:19.589+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [30731131]:  Starting store flush...
2017-10-03 17:56:19.906+0000 INFO [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 30731131 to [.../graph.db/neostore.counts.db.a], from [.../graph.db/neostore.counts.db.b].
2017-10-03 17:56:19.936+0000 INFO [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 30731131 to [.../graph.db/neostore.counts.db.a], from [.../graph.db/neostore.counts.db.b].
2017-10-03 17:56:20.088+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [30731131]:  Store flush completed
2017-10-03 17:56:20.089+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [30731131]:  Starting appending check point entry into the tx log...
2017-10-03 17:56:20.091+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [30731131]:  Appending check point entry into the tx log completed
2017-10-03 17:56:20.091+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [30731131]:  Check pointing completed
```

Log pruning like this:

```
2017-10-03 17:56:20.091+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [12546]:  Starting log pruning.
2017-10-03 17:56:20.091+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [12546]:  Log pruning complete.
```

Log rotation like this:

```
2017-10-03 19:56:16.131+0000 INFO [o.n.k.NeoStoreDataSource] Rotating log version:45
2017-10-03 19:56:16.132+0000 INFO [o.n.k.NeoStoreDataSource] Opened logical log [.../graph.db/neostore.transaction.db.46] version=46, lastTxId=30731176 (clean)
2017-10-03 19:56:16.133+0000 INFO [o.n.k.NeoStoreDataSource] Finished rotating log version:45
```

These events happen quite frequently so a more consice format will make it easier to read and take up less space in the log.
The logging has been changed to look like, for check pointing:

```
2017-10-11 10:01:00.050+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by scheduler for tx count threshold @ txId: 3193169 checkpoint started...
2017-10-11 10:01:00.092+0000 INFO [o.n.k.i.s.c.CountsTracker] Rotated counts store at transaction 3199085 to [.../graph.db/neostore.counts.db.b], from [.../graph.db/neostore.counts.db.a].
2017-10-11 10:01:00.317+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Checkpoint triggered by scheduler for tx count threshold @ txId: 3193169 checkpoint completed in 245ms
```

Log pruning:
```
2017-10-11 10:01:00.359+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Pruned log versions 0-3, last checkpoint was made in version 7
```

Log rotation:
```
2017-10-11 10:01:01.271+0000 INFO [o.n.k.NeoStoreDataSource] Rotated to transaction log [.../graph.db/neostore.transaction.db.8] version=8, last transaction in previous log=3585572
```

which is less text and more information than the previous format had.

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
Looks good except one thing I think it should target 3.4 only

**Comment by tinwelint** [comment]
I wanted to help making sense of logs from earlier versions too. Would it harm maint releases you think?

**Comment by MishaDemianenko** [comment]
It's hard to say how many people do some sort automatic monitoring or parsing of our logs would be nice if we do not break those

**Comment by tinwelint** [comment]
You've got a point there... it's fine, I'll retarget for 3.4 instead

**Comment by tinwelint** [comment]
@MishaDemianenko done

**Comment by MishaDemianenko** [comment]
@tinwelint unfortunately checkstyle is complaining now

**Comment by tinwelint** [comment]
@MishaDemianenko  Checkstyle fixed, and also rebased due to some test hanging (which was recently ignored/fixed I recall).

**Pull request merged**
