### PR TITLE
Merge neo4j-logging into kernel and add documentation

### PR DESCRIPTION
**Pull request by cleishm**
Implementations are moved into an impl package for now, as they depend on currently undocumented classes like `org.neo4j.function.Supplier` (a placeholder until building on Java 8) and are only used in kernel and server.

### CODE REVIEW

**Comment by lutovich** [comment]
@cleishm could you please add some description why neo4j-logging should be in kernel?

**Comment by cleishm** [comment]
@lutovich As it stands currently, it's not useful as an independent library, due to the use of classes like `org.neo4j.function.Supplier`. We should change that after we build with Java8.

**Comment by tinwelint** [comment]
Seems like an unnecessary change. `org.neo4j.function.Supplier` lives in `primitive-collections` btw.

The next case where we'd need logging w/o kernel we'd have to break it out again. If it's a matter of visibility we can change the package w/o folding into kernel.

**Comment by cleishm** [comment]
The packages remain the same, simply the module has changed. I could leave the interfaces in a separate module, but that is rather pointless given nothing needs them without also needing the kernel.

As for moving away from a monolithic design: doing so via maven modules is still a point of discussion, and there are strong arguments against that. Doing so via packages is sensible, and the logging interfaces remain in a separate package, so that's good.

**Comment by digitalstain** [comment]
@cleishm There is no clear need to merge logging into kernel as far as i can tell and i tend to agree that this direction, as we have things configured now, is the reverse of what we are aiming for. How about we resolve the discussion about modularity first and then see if this merge is necessary?

**Comment by cleishm** [comment]
Will reopen after #4554

**Pull request closed without merging**
