### PR TITLE
Add enterprise neo4j-harness

### PR DESCRIPTION
**Pull request by FylmTM**
- Enterprise test server builders
- Enterprise JUnit rule
- Basic tests to ensure that server can be started
- Add test project to manual module

### CODE REVIEW

**Comment by nawroth** [comment]
The CI build was actually green, but the link is messed up.

The PR needs a rebase though.

Also, it would be good if the test project actually performs something that would fail unless it's executed on Enterprise. (Or did I just miss something?)

**Comment by FylmTM** [comment]
@nawroth Maybe I can try to create `property existence` constraint. Is it good enough?

**Comment by nawroth** [comment]
That sounds good to me.

**Comment by FylmTM** [comment]
@nawroth I have updated code:
Enterprise harness now tries to create `property existence` index. (in tests and test project)

Unfortunately I can't get successful local build - Cypher3.0 is unable to compile due to crazy scala errors.

**Comment by nawroth** [comment]
I rebased it on top of current 3.0, see https://github.com/neo4j/neo4j/issues/5872
It looked good locally.

**Comment by FylmTM** [comment]
@nawroth I fixed test failures.
There was an issue in how depencies in maven were loaded in test scope.

Can you reopen this PR?

**Comment by nawroth** [comment]
Oops, can't reopen after a forced push. I pushed it to my PR instead!

**Pull request closed without merging**
