### PR TITLE
fix netty leak

### PR DESCRIPTION
**Pull request by catslink**
#12265

### CODE REVIEW

**Comment by catslink** [comment]
I have sent mail to sign CLA.

**Comment by klaren** [comment]
Hi and thanks for your pull request!

The CLA is received and the check should turn green momentarily.

**Comment by klaren** [comment]
The commit is created with a different email which is not the same email that signed the CLA. Could you please update one of them so it matches?

**Comment by catslink** [comment]
@klaren please re-check, they should be same now. Thanks.

**Comment by klaren** [comment]
Everything looks good with the CLA. There were a few failing tests due to double releasing of resources so I had to move the try-finally down one lever to the `ProtocolHandshaker` and now every test is passing.

**Comment by catslink** [comment]
@klaren  I don't have chance to look that code yet, but wonder what's next for the buffer leak?  What does "double releasing of resources" mean, is there any product code to release that buffer or just test code that does it?

**Comment by klaren** [comment]
The buffer was released inside the `ProtocolHandshaker` as well. I move your code there to prevent this: https://github.com/neo4j/neo4j/commit/102e930de9b875a65305a76906d13d35e9783c81

**Comment by catslink** [comment]
Yes, your change matches the log. Will it be merged into build?

**Comment by klaren** [comment]
It's already merged by the build agent as you can see above. It will be part of the upcoming releases.

It is a bit confusing that the PR is marked as closed, but the github API does not allow our automated build system to mark it as merged.

**Comment by catslink** [comment]
Saw it. Expecting the new release. But I still have a question on ```ProtocolHandshaker``` : My debug.log is fullfilled with WARN log ```Unsupported connection type: 'HTTP'. Bolt protocol only operates over a TCP connection or WebSocket.``` What kind of request invokes that? Is there any action to avoid the message flood? Or is it reasonable to log it?

**Comment by klaren** [comment]
Someone is sending regular HTTP requests to your bolt listening address(default :7687) and not WebSocket requests. Those request should go to a different port(default :7474).

**Pull request closed without merging**
