### PR TITLE
Add graphdb-api as javadoc source

### PR DESCRIPTION
**Pull request by nawroth**
Also move to use dependencies instead of file locations.

### CODE REVIEW

**Comment by nawroth** [comment]
This PR now puts the Procedure javadocs in place as well.

**Comment by jjaderberg** [comment]
I think the enterprise management Javadocs are missing. The package `org.neo4j.management` used to part of the advanced module and the Javadocs seem to have been lost when it was moved under enterprise. Otherwise it looks good and seems to build nicely with Java 8 linting.

**Comment by jjaderberg** [comment]
Actually, I just noticed the change to the linting scope. What's the thinking there?

**Comment by nawroth** [comment]
@jjaderberg good catch! `org.neo4j.management` is back now.

**Pull request merged**
