### PR TITLE
Add settings to enable confirm-on-page-exit prompt.

### PR DESCRIPTION
**Pull request by oskarhane**

### CODE REVIEW

**Comment by jexp** [comment]
Where did the requirement come from? This is something I never heard of as a request from anyone?

**Comment by maxdemarzi** [comment]
I requested as people in the class kept losing their query log by accidentally doing a "back page" on their browser.

**Comment by apcj** [comment]
We're not sure that is the best solution to the problem; people generally find 'are you sure?' messages annoying. An alternative is to add entries to the browser history for each action such as running a query or entering full-screen mode, so that the back button doesn't generally leave the page but just takes you back to a previous state.

**Comment by jexp** [comment]
I agree "do you really want" messages are just annoying, I like that approach more ! 
E.g. sometimes I had it that I accidentally hit arrow up after having typed a large query and then it was gone.

**Pull request closed without merging**
