### PR TITLE
Have you tried turning it off and on again?

### PR DESCRIPTION
**Pull request by maxdemarzi**

### CODE REVIEW

**Comment by lutovich** [comment]
I think this looks rude.
-1 for this message.

**Comment by oskarhane** [comment]
I'm all for changing the current message, but not to something that suggests that the server should be restarted.

**Comment by jotomo** [comment]
Funnily(?) enough, restarting the server might just cause this message to be displayed, as the server currently can take up to a full minute to reconnect, see #4929 (heartbeat defaults to 60s, which is better than 50 times a second, but doesn't help with this message).
Here's an idea: increase the heartbeat to 1-5s when the connection has been lost and change the message to indicate the UI is retrying. Something like _The connection to the Neo4j server has been lost. Trying to reconnect ..._ perhaps?
The 2nd sentence of that message (both old and new) are inapprioprate as it's the wrong place for witty jokes IMO: if there's a problem and it's not just a test server, meaning the admin/user is under pressure, wittyness easily backfires.
(P.S. love IT Crowd references, but not in this particular situation ;-) ).

**Comment by oskarhane** [comment]
Ah, I missed the IT Crowd reference. Makes it more funny but still...  
Anyway, I like @jotomo's suggestion. Closing this.

**Comment by maxdemarzi** [comment]
people

**Comment by jotomo** [comment]
@maxdemarzi That's it, I'm gonna watch the special again. After hiding the internet, so it can't get me. We're not doing that? Ahhh ;-)

**Pull request closed without merging**
