### PR TITLE
Initial work on making javadocs build on Java 8.

### PR DESCRIPTION
**Pull request by jotomo**
Java 8 treats certain problems with javadoc as errors, which were warnings prior to Java 8. A full build of Neo4j using Java 8 thus fails with a lot of javadoc errors. This PR fixes the javadoc of a bunch of modules (needed something to distract me).
Not sure when or if I'll pick this up again, so I'm putting this up to be merged. Shouldn't be a problem, since this can nicely be done iteratively.
There are some classes of errors remaining where an email is provided like "@author Name <email>", where the <> characters need to be escaped. I was wondering whether they're worth being fixed, can be dropped or should be replaced by the GH handle?
Overall, I only tended to errors, not warnings. There's a _"screw this, just ignore the errors"_-flag, but it's unknown to JDK7, so using it would make the build work _only_ on JDK8. The question I'm asking (myself, and now you guys) is what value lies in javadocs and how much effort should be put into this?

### CODE REVIEW

**Comment by jakewins** [comment]
@jotomo generally, we care about following the javadoc rules for publicly documented classes. For non-public code we're all for docs, but not as strict about the formatting. Still, it would be useful to be able to build the internal docs with the javadoc tool as well.

Eg; I'd focus on the classes/interfaces you see here: http://neo4j.com/docs/stable/javadocs/

On @author notes - you can remove these if you come across them, they are inserted, generally, by IDEs. We use git blame to track authorship, whoever created the class initially is not particularly relevant

PR looks good to me, I'm happy to merge if you rebase it :)

**Comment by jotomo** [comment]
@jakewins  I don't think it's possible to apply different levels of  checks on specific packages, just modules. So to get it to compile all javadoc syntax errors need to be fixed (proofreading content & meaning of public classes would be a separate task).
Are there any plans on using JDK8? IIRC when compiler level 1.7 is set, Intellij inserts javadoc that JDK8 will complains about, so cleaning it up now might mean bad javadoc gets into the codebase again (since JDK7 won't complain). Though the amount would probably be small.
Note: I started this because the Maven product build (-DfullBuild) fails on JDK8 and I thought you probably, eventually, want to build on JDK8 too.
P.S. Is the build hanging? Rebased build is running for about 5h now.

**Comment by jakewins** [comment]
@jotomo hmm, you're right. We do build on JDK8, but we don't build javadocs. +1 on having people use java 8 in intellij. I think many people stay on java 7 since we're still maintaining older releases that need to be java 7 compatible, but this should change in the coming months as we move to java 8 only.

In any case - if you want to keep going with this, I'm happy to keep merging it. There's a lot of javadoc to cover, but any increment helps. If we can just get it to a point where it builds, we can set up a java 8 javadoc built to "lock it in", so to speak.

Ping @nawroth, is there a plan for java 8 javadocs?

Ps: Yep, build had hung. Unrelated to this, restarted it.

**Comment by nawroth** [comment]
Since version 2.2.2 Neo4j supports Java 8 so it would make sense to be able to build all of it using JDK8.

How about this plan:
1. Get the javadocs in the `2.2` branch free from errors when using JDK8.
2. Switch the documentation build for `2.2` to use JDK8.
3. Fix the javadoc errors in the `2.3` branch that weren't fixed by merging in the `2.2` fixes.
4. Switch the documentation build for `2.3` to use JDK8.

**Comment by jotomo** [comment]
@nawroth Sounds sensible to me. What exactly is the _documentation build_? I'm just running _mvn javadoc:javadoc_ in the root folder so far.

**Comment by cleishm** [comment]
Just to add some color to what @nawroth said: we support _running_ on JVM 8, as of Neo4j 2.2.2. Building with JDK 8 will be something we move toward later, probably for our 3.0 release (we need to keep JVM 7 support until then).

That said: good to make these sort of changes well in advance!

**Comment by nawroth** [comment]
@jotomo By "documentation build" I mean the daily build on our build servers executing something along the lines of `mvn clean verify -DdocsBuild`. It also publishes the results, for example: http://neo4j.com/docs/2.2-SNAPSHOT/javadocs/

The most important javadocs - the ones we publish online - are created by the `neo4j-javadoc` module. To build it you can do `cd manual/javadocs && mvn clean install`. Note that `javadoc:javadoc` won't work in this case.

**Comment by jotomo** [comment]
@nawroth @cleishm Thanks for the infos!
@jakewins Rebased and ready to merge.

**Comment by jotomo** [comment]
@jakewins Anything holding you back from pushing the merge button? ;-)

**Comment by jotomo** [comment]
@jakewins Thanks for this and the help with the IntelliJ setup. The _annotation processor_ hint was the missing bit.

**Comment by jakewins** [comment]
@jotomo more than happy to help :) Lots of PRs from you lately, always appreciated!

**Pull request merged**
