### PR TITLE
Take into account lazyness and eagerness of logical operators when planning

### PR DESCRIPTION
**Pull request by davidegrohmann**

### CODE REVIEW

**Comment by davidegrohmann** [comment]
@boggle @systay can you have a look at this? I would like some feedback.
Mind that this changes are not tested and some cleanup is needed, so this is not ready to get in as it is.
Running the problematic query with these changes produced the same plan as Greedy when using IDP.

**Comment by systay** [comment]
I think this is definitely a step in the right direction. Thanks for taking it on, @davidegrohmann.

Would it make things even better if we calculated how large part of the results we are actually after? What I am thinking is - we know the estimated cardinality for the result, and we know how many rows the user is asking for. Could we use the relative difference between these two numbers as a multiplier for the cost?

**Comment by craigtaverner** [comment]
I understood the boolean flag as the first step, switch the eager/lazy option on/off. But the next step would be to compare the estimated rows with the limit and scale the switch accordingly. So an 'importance-of-laziness' factor could be passed in based on something like (1-limit/rows), or something. Then the cost increase to eager operators would be scaled by this factor, which should be near zero (no increase) if limit is close to estimated rows, and be a big factor if limit is much smaller.

**Comment by davidegrohmann** [comment]
@systay absolutely! I was thinking the same to compute the diff between the cardinality and the limit of rows and act from there. But we can do that only if the limit expression is a constant and not a parameter.

**Pull request merged**
