### PR TITLE
3.5: Pin urls to 3.5 documentation

### PR DESCRIPTION
**Pull request by jsoref**
Error messages from Neo4J 3.5 shouldn't point to the current operations manual as that's the operations manual for 4.0...

### CODE REVIEW

**Comment by klaren** [comment]
Nice find!

All the changes look good. I would prefer we used a maven property so we don't have to manually update all the locations every release. I could add that before merging it if that is okay with you.

Thanks for your contribution!

**Review by klaren — APPROVED** [review]

**Comment by jsoref** [comment]
@klaren: I run across maven properties, so I vaguely know they exist, but I'm glad to let you do that work. Thanks

**Comment by jsoref** [comment]
@klaren: did you add a later commit for the macro?

**Comment by klaren** [comment]
@jsoref I opted to only do it for the code
https://github.com/neo4j/neo4j/commit/f157a26c57a3206d964f5130b30c9dcda7c196fb

Apparently, the URL differs a bit from version to version so a simple variable would not do the trick since you have to verify every single link anyway.

**Pull request closed without merging**
