### PR TITLE
Fix neo4j start with lsof>=4.87

### PR DESCRIPTION
**Pull request by spacecowboy**
Also corrects some indentation.

PR against 2.2 instead of 2.3 after discussion here: https://github.com/neo4j/neo4j/pull/5569#issuecomment-147046006

Issues related to this:
#5443
#3414
#4505
#5624

### CODE REVIEW

**Comment by spacecowboy** [comment]
@thobe  changed it back after your feedback.

For completeness, I have now tested this change (with success) against all versions of lsof I could get a hold of:
- 4.77
- 4.78
- 4.80
- 4.81
- 4.82
- 4.83
- 4.84
- 4.85
- 4.86
- 4.87
- 4.88
- 4.89

**Comment by thobe** [comment]
Looks good.

**Comment by davidegrohmann** [comment]
@spacecowboy Is it really necessary to have 2 commits? Why not squash them?

**Comment by spacecowboy** [comment]
@davidegrohmann squashed

**Pull request merged**
