### PR TITLE
Break out fileSystem method from OutsideWorld interface

### PR DESCRIPTION
**Pull request by burqen**
And have all commands use provided FileSystemAbstraction instead of creating their own.

### CODE REVIEW

**Comment by burqen** [comment]
@benbc What do you say about this?

**Comment by benbc** [comment]
@burqen I say: "why?"

**Comment by burqen** [comment]
Decouple file system from output makes the responsibility of the interface clearer.
And having all commands use provided `FileSystemAbstraction` would be the behaviour I would expect.

**Comment by burqen** [comment]
The reason I ended up here is it causes a compilation error in blockdevice where we would have to provide null for file system abstraction.

**Comment by benbc** [comment]
> having all commands use provided FileSystemAbstraction would be the behaviour I would expect

Does refer to the fix in `DumpCommand` to avoid instantiating the FSA? You are certainly right there; well spotted.

I'm not sure that your change makes the responsibility of the interface cleaner. I think it's reasonable to have a single collaborator that encapsulates all I/O. I think generally your change just makes the provision of fakes in tests more of a pain (c.f. the various places that you've created a mock FSA just in order to fake it out.

However if you've got a genuine problem in blockdevice, then we must fix it. Can you expand on that, I haven't understood what you are saying?

**Comment by burqen** [comment]
@benbc I don't have any real problem right now, so I don't have any strong opinion about this. Will gladly close it as you don't find it helpful :)

**Pull request closed without merging**
