### PR TITLE
Add enterprise neo4j-harness

### PR DESCRIPTION
**Pull request by jakewins**
- Enterprise test server builders
- Enterprise JUnit rule
- Basic tests to ensure that server can be started

### CODE REVIEW

**Comment by jakewins** [comment]
Rebased towards 3.x from https://github.com/neo4j/neo4j/pull/5675/commits

**Comment by nawroth** [comment]
I think this should happen before we merge it: https://github.com/neo4j/neo4j/pull/5675#issuecomment-150178496

**Comment by jakewins** [comment]
@nawroth makes sense. Lets wait on @FylmTM for that update.

**Comment by FylmTM** [comment]
@jakewins  @nawroth 

I have updated and opened new PR #5801.
- Updated to work with 3.0
- Added test project

**Pull request closed without merging**
