### PR TITLE
Allow expressions for URL in LOAD CSV

### PR DESCRIPTION
**Pull request by pontusmelke**

### CODE REVIEW

**Comment by chrisvest** [comment]
ltjbo6m

**Comment by nawroth** [comment]
I think this should get mentioned in the manual.
How about here? https://github.com/neo4j/neo4j/blame/2.3/manual/cypher/cypher-docs/src/docs/dev/ql/load-csv/index.asciidoc#L9

**Comment by pontusmelke** [comment]
@nawroth Added docs.

**Comment by nawroth** [comment]
@pontusmelke Thanks!

**Pull request merged**
