### PR TITLE
Break TLS and Auth into separate 'security' module

### PR DESCRIPTION
**Pull request by jakewins**
A step towards breaking the monolithic server codebase into purpose-specific components, and a required step to organize the dependency tree for new remoting vis-a-vis X.509 certs and auth.

### CODE REVIEW

**Comment by cleishm** [comment]
Is this strictly necessary? What about only moving the interfaces? Perhaps into a neo4j-server-api?

**Comment by jakewins** [comment]
@cleishm what is the benefit of keeping certificate generation and auth inside the server module?

**Comment by cleishm** [comment]
Best to answer the question I posed first :)

**Comment by jakewins** [comment]
These are two security-related services that stand on their own, and that have dependent modules beyond the REST implementation that currently lives in the 'server' module. Currently new remoting, but this will expand to include the transaction state engine for authorization.

That dependency hierarchy between services makes it clear to me that at least the API needs to be separate. And given that, I don't see how having the service implementation in a module unrelated to the service in question will help, ergo I suggest we keep the services together with their APIs, in service-specific modules, for now.

**Pull request closed without merging**
