### PR TITLE
Constraint boundary push

### PR DESCRIPTION
**Pull request by fickludd**
Pushed the constraint boundary pretty far. This should not introduce any functional changes.

Commits are slightly overlapping, but each is fully functional. I would review this as a whole.

### CODE REVIEW

**Review by chrisvest — APPROVED** [review]
Tedious, but looks alright.

**Comment by chrisvest** [comment]
@fickludd You have a bunch of test failures, so not entirely without functional changes it seems.

**Comment by chrisvest** [comment]
@fickludd It also needs a rebase now.

**Comment by fickludd** [comment]
@chrisvest Test failures? That's why I put in the defensive *should* in the PR description. It does change some exception messages to be honest. Hoping I managed to rebase and fix now, but not having the most precise day, so who knows =P.

**Pull request merged**
