### PR TITLE
fix typo in traversal.asciidoc

### PR DESCRIPTION
**Pull request by manonthemat**

### CODE REVIEW

**Comment by spacecowboy** [comment]
Nice catch @manonthemat 

Could you sign our CLA please? Once you do, I can merge your PR. See http://neo4j.com/developer/cla/  (you only need to send an email)

Additional information can be found here: http://neo4j.com/developer/contributing-code/

**Comment by manonthemat** [comment]
Jonas, I signed the CLA on September 18th 2015.

**Comment by spacecowboy** [comment]
Ah, so you had. Someone had neglected to add you to the list however (fixed that).

**Comment by manonthemat** [comment]
Thanks a lot. 👍

**Pull request merged**
