### PR TITLE
Adds IndexCapability#limitations

### PR DESCRIPTION
**Pull request by tinwelint**
Where additional flags can be raised about limitations
in a particular index implementation. Such flags can be used
to create e.g. notifications.

### CODE REVIEW

**Review by burqen — CHANGES_REQUESTED** [review]
Implementation of IndexLimitation looks nice!
Got some questions around message:
1. Is it well understod among users that a wildcard query includes both contains and ends with?
2. It would be nice to provide user with suggestion on what to do instead if they run into this. Will that be part of some other PR?
3. Where will those messages eventually pop out? (With following PRs)

**Comment by tinwelint** [comment]
I too am not sure about those error messages. I was hoping for the Cypher planner to have some way of providing more context, like which index it's about and so on, because without additional context this will look strange anyway. I suggest we don't quite care about those message right now and tweak them when they get integrated.

**Comment by burqen** [comment]
@tinwelint That sounds fine. I assumed you had some integration commits lined up.

**Review by burqen — APPROVED** [review]

**Comment by tinwelint** [comment]
#11769 builds on top of this and will be merged anyway, so closing this one.

**Pull request closed without merging**
