### PR TITLE
Always migrate using batch importer.

### PR DESCRIPTION
**Pull request by maxsumrall**
Migration times did not seem to improve by doing a direct migration.
 However we still use the direct migration for migrating token stores.

### CODE REVIEW

**Comment by chrisvest** [comment]
You can try implementing the direct migration with the `PageCursor.copyTo` functionality of the page cache. It's a little tricky to get right, due to differing record sizes, but it should be considerably faster than the record-by-record migration the direct store migrator does currently.

**Comment by tinwelint** [comment]
@chrisvest that doesn't really work here since we need to transform the bits and bytes in each record from one format to another in between. Is there some fancy way we could do that?

**Comment by chrisvest** [comment]
@tinwelint Well, okay. If the RecordCursor was able to write records as well, then you could get both your format conversion and only do the minimum amount of pin/unpins.

**Comment by tinwelint** [comment]
@chrisvest yes I've been about to add such a record updater cursor as well, just haven't found the proper driver yet. It makes sense to have that.

**Comment by tinwelint** [comment]
@maxsumrall needs rebase, also found a diff tool in ha-robustness I'm going to use to further verify migration, and which we should potentially incorporate in upgrade tests actually.

**Pull request merged**
