### PR TITLE
Fix flaky TransactionThroughMasterSwitchStressIT

### PR DESCRIPTION
**Pull request by burqen**
Master go down
Server 2 is waiting for heartbeat
Master go up and re-election happens.
Server 2 will not join cluster because he still think old master is master and he's waiting for his heartbeat.
Because the heartbeat time (40 s) is larger than join cluster timeout (30 s)
it can happen that the cluster fails to form before Server 2 realise that he should re-join cluster.

Setting heartbeat timeout to a lower value should fix this.
Adding additional allSeesAllAsAvailable should make it more clear where we fail in the future, if this fix is not correct.

### CODE REVIEW

**Comment by chrisvest** [comment]
@burqen Should we reflect on the default timeout settings based on this?

**Comment by burqen** [comment]
@chrisvest Possibly.
But, in the normal case operation will proceed with Master and Server 1 being the only once available in the cluster. Server 2 will eventually fail and re-join the cluster. It's just a matter ClusterRule being a little bit picky about `allSeeAllAsAvailable` when starting up.

To be honest I don't know how `heartbeat_timeout` and `join_timeout` depend on each other and how the defaults was settled upon. Experimenting with new timeouts should wait until 3.1 GA goes out anyway.

Do you have any suggestions on how to go about this?

**Comment by martinfurmanski** [comment]
Have you seen that join_timeout is 60s in ClusterRule?

**Comment by burqen** [comment]
@martinfurmanski No, I have not, but you are right. Back to the drawing board. Closing.

**Pull request closed without merging**
