### PR TITLE
Further StoreLogService creation simplification. Remove factory methods that return Builder from StoreLogService

### PR DESCRIPTION
**Pull request by MishaDemianenko**
Switch to StoreLogService builder creation in cases where factory methods from StoreLogService with builder as result where used before.

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@cleishm what do you think about this way of StoreLogService creation.

**Comment by cleishm** [comment]
@MishaDemianenko What's the advantage you see there? Is it just stylistic? My preference is probably different then, as to me:

```
new StoreLogService.Builder().withUserLogProvider( logProvider ).inStoreDirectory( fs, storeDir )
```

is more complicated to read than

```
StoreLogService.withUserLogProvider( logProvider ).inStoreDirectory( fs, storeDir );
```

Perhaps we can chat about why that is the case. Or, alternatively, I've misunderstood what you're aiming for?

**Comment by MishaDemianenko** [comment]
Restore factory methods and add private constructor into builders.

**Comment by tinwelint** [comment]
It looks to me like the two commits in this PR should be merged into one since the second reverts some changes of the first.

**Pull request merged**
