### PR TITLE
Removed PMD maven plugin

### PR DESCRIPTION
**Pull request by lutovich**

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@lutovich why we removing PMD and instead of using it?

**Comment by jakewins** [comment]
@lutovich +1 on @MishaDemianenko's point, would be really nice to track (and ideally cap in CI) some of the things PMD gives us.

**Comment by lutovich** [comment]
@MishaDemianenko, @jakewins this plugin was disabled for more than 2 years and was configured only for community/cypher which has practically no java code.
I agree that we need some static analysis tool but think that it should be introduced from scratch and this PMD file does not have much value now.

**Comment by jakewins** [comment]
@lutovich ait, fairynuf

**Comment by MishaDemianenko** [comment]
@lutovich agree that it's reasonable to delete this particular config, still lets add a card to setup sonar somewhere then?

**Comment by lutovich** [comment]
@MishaDemianenko done

**Comment by MishaDemianenko** [comment]
:bow:

**Pull request merged**
