### PR TITLE
Better error message for missing credentials

### PR DESCRIPTION
**Pull request by pontusmelke**
- Removed cryptic unique identifier in output
- Better error message when missing username and password

### CODE REVIEW

**Comment by zhenlineo** [comment]
May I ask what is this `identifier`? What it was used before? Besides this question, this PR is good for me.

**Comment by pontusmelke** [comment]
@zhenlineo it was introduced as a means for the driver to identify different neo4j instances, but it isn't used so I think it is only confusing people atm.

**Comment by zhenlineo** [comment]
The failing tests are related. After they are fixed, this is also ready to go!

**Comment by pontusmelke** [comment]
@zhenlineo fixed

**Pull request merged**
