### PR TITLE
Fix flaky ListQueriesProcedureTest

### PR DESCRIPTION
**Pull request by chrisvest**

### CODE REVIEW

**Comment by chrisvest** [comment]
@thobe Does this one still make sense given #8672?

**Comment by thobe** [comment]
@chrisvest you fix a different thing here. #8672 fixes what has been failing the build occasionally, but the change you proposed here still looks good to me.

**Comment by thobe** [comment]
The test failure is unrelated. So I could merge this. But since it touches the same file, I would prefer to see #8672 merged first to minimise the risk from conflicts.

**Comment by chrisvest** [comment]
@thobe Merged it.

**Pull request merged**
