### PR TITLE
Implement UncloseableDirectory using Lucene's FilterDirectory

### PR DESCRIPTION
**Pull request by uschindler**
Hi @jexp @MishaDemianenko ,
this is more or less a Test PR to establish the workflow. It is just a stupid simple cleanup.
I think this should be easy to merge :-)

### CODE REVIEW

**Comment by uschindler** [comment]
I have no idea why the checks failed (and I cannot access TeamCity).

**Comment by MishaDemianenko** [comment]
Hi @uschindler TeamCity failing because it can't fine contributor license agreement from you. Have you sign it already? Just in case you can find all the details here: https://neo4j.com/developer/cla/

**Comment by uschindler** [comment]
Oh no I did not. Will do!

**Comment by uschindler** [comment]
Done, see mail folder.

**Comment by MishaDemianenko** [comment]
@uschindler ok, CLA is there, TC now should allow you to trigger builds. 
Also i re-trigger all PR build so if everything is fine those should be green after some time

**Pull request merged**
