### PR TITLE
Cleanup, use gen instead of generation in index module

### PR DESCRIPTION
**Pull request by burqen**
In code, be consistent with using 'gen' instead of 'generation'.
In comments, use 'generation'

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@burqen to be quite honest I not quite sure I understand why we need to do this and use gen instead of generation because it makes code/docs more cryptic then before and require even more context then before.

**Comment by burqen** [comment]
@MishaDemianenko That's exactly the kind of feedback I was looking for!
What do you think about doing it the other way instead? To use 'generation' everywhere?

**Comment by MishaDemianenko** [comment]
@burqen i think that would be better since you do not need to guess what `gen` by itself means 👍

**Comment by burqen** [comment]
@MishaDemianenko Checkout #9030 
Closing this PR

**Pull request closed without merging**
