### PR TITLE
Fix NPE after reopen the IndexReader

### PR DESCRIPTION
**Pull request by thmarx**
According to the lucene docs, the method DirectoryReader.openIfChanged returns null if there are not changes.

changelog: Fixed NPE after reopen of IndexReader in legacy index

### CODE REVIEW

**Comment by lutovich** [comment]
Hello @thmarx, thanks for the fix, it seems valid.
Could you please add a test or couple that expose this issue?
It is also needed to sign CLA, see http://neo4j.com/developer/contributing-code/.

**Update:** CLA signed, just noticed it, sorry :)

**Comment by thmarx** [comment]
Hi,

Test was added.
It was a hard to reproduce with a simple unit test. Our production code is much more complex and it took some time to extract the correct parts. 
Even FullTxData is realy deep in the code and absolutly hard to test.

**Comment by lutovich** [comment]
@thmarx thanks for the test! could you please rebase on the most recent 3.1 to make those test failures go away? otherwise, I can probably cherry-pick your commits and push them directly.

**Comment by thmarx** [comment]
@lutovich I've tried to rebase, but now the merged commits are part of the pull request. is this a problem?

**Comment by lutovich** [comment]
@thmarx yeah, history looks quite strange now. there should be only your commits visible after a correct rebase. you can try the following (probably a bit barbarian) steps to create a clean history:

```
git remote add upstream https://github.com/neo4j/neo4j  // add neo4j/neo4j as upstream
git fetch upstream  // pull everything from neo4j/neo4j
git reset --hard upsream/3.1  // make local 3.1 branch look the same as in neo4j/neo4j
git cherry-pick 143ab3d  // add 'Fix NPE after reopen the IndexReader' commit to the current branch
git cherry-pick 2cff692  // add 'add unit test for reopen issue' commit to the current branch
git cherry-pick 6b406a2  // add 'fix checkstyle issues' commit to the current branch 
git push -f origin 3.1  // make thmarx/neo4j reflect these changes
```

These steps assume that you've cloned from your fork `thmarx/neo4j` and have it as `origin`. This could be checked with `git remote -v` command.

Hope this helps :)

**Comment by thmarx** [comment]
@lutovich many thanks for the help.

**Comment by lutovich** [comment]
@thmarx merged, thanks a lot for the fix!
I've added a line to the PR description so it'll be reflected in the changelogs.

**Pull request merged**
