### PR TITLE
Fix issue #6836 about error message

### LINKED ISSUE #6836: Incorrect error message when creating 2-dimensional arrays
When attempting to set a property value to a two dimensional array or an array with multiple null values ([null,null]), an incorrect/unhelpful error is raised.

**Neo4j Version:** enterprise-2.3.2
**Operating System:** OSX 10.11.3
**API:** Browser
### Steps to reproduce
1. Run query `MATCH (n) with n limit 1 set n.arrayProp = [['test'],['strings’]]` 
2. Run query `MATCH (n) with n limit 1 set n.nullProp = [null,null]`
### Expected behavior

error message should be `Property values can only be of primitive types or arrays thereof`
### Actual behavior

error message is `Collections containing mixed types can not be stored in properties.`

### PR DESCRIPTION
**Pull request by jonasagx**
Changelog: Fixed #6836 regarding incorrect error message for properties of arrays of arrays

### CODE REVIEW

**Comment by jonasagx** [comment]
Fix for #8682

**Comment by spacecowboy** [comment]
@jonasagx thanks for the pr!

Which issue are  you referring to? Your `Fix for ...` only refers back to this PR.

EDIT: nvm, correct issue in title. Editing your PR message so GitHub does the right thing

**Comment by jonasagx** [comment]
Sorry @spacecowboy for making it confusing. Is there something else I can do to make it right?

Also. It says the all the tests failed -- how can I fix that? I'm not aware of what is going on with TeamCity tests. Thanks

**Comment by spacecowboy** [comment]
@jonasagx they are all marked as failed because you are not on our list of approved contributors. Please have a look at https://neo4j.com/developer/cla/

It's as easy as sending an email. Ping me when you've done so and I'll make sure TC re-runs the tests

**Comment by jonasagx** [comment]
@spacecowboy I've signed the agreement

**Review by thobe — APPROVED** [review]
Looks like a good improvement to me.

**Comment by spacecowboy** [comment]
Tools Compile failure is unrelated

**Pull request merged**
