### PR TITLE
Jvm metrics prefix should be just 'vm'

### PR DESCRIPTION
**Pull request by lassewesth**
@davidegrohmann Mind if I change this so it looks like what the old plugin did?

### CODE REVIEW

**Comment by chrisvest** [comment]
@lassewesth Are these the only metrics who had their prefixes changed?

**Comment by davidegrohmann** [comment]
@lassewesth I don't like this change. I have added `neo4j.` as prefix to be consistent with https://github.com/neo4j/neo4j/blob/2.3/enterprise/metrics/src/main/java/org/neo4j/metrics/source/DBMetrics.java and https://github.com/neo4j/neo4j/blob/2.3/enterprise/metrics/src/main/java/org/neo4j/metrics/source/NetworkMetrics.java

Why do we need to remove the `neo4j.` prefix?

**Comment by lassewesth** [comment]
@chrisvest Those are the only metrics _that I/ we have used_ that have changed, it seems

**Comment by lassewesth** [comment]
@chrisvest I.e. nothing else seems broken.

**Comment by davidegrohmann** [comment]
@lassewesth alright, I'll merge this in

**Pull request merged**
