### PR TITLE
Code generation refactorings around equality 

### PR DESCRIPTION
**Pull request by pontusmelke**
Fixes include:
- Bug fix, properly handle comparing large floating point numbers without precision loss
- Only create NodeProxy and RelationshipProxy when doing the actual final projection
- Updated `Equals`, `Or`, and `Not` to be smarter about nullability and types
- Parameters are now read into local variables and not read from hash map.
- Miscellaneous minor bug fixes

### CODE REVIEW

**Comment by thobe** [comment]
"ternaryOr" takes only two arguments, so it would be binary, not ternary. No?
Similarly "ternaryNot" only takes a single argument, making it unary, not ternary.
These names are confusing.

I also object the placement and naming of some of the classes.

See comments on the commits.

**Comment by pontusmelke** [comment]
I agree with the placement, but using ternary as in `ternary logic` seems like reasonable naming to me. 
https://en.wikipedia.org/wiki/Three-valued_logic 
It is ternary in output not input.

**Comment by thobe** [comment]
@pontusmelke ah, it referring to ternary logic makes sense. Thanks for the explanation. Could we make it more obvious to other readers of the code somehow?

**Comment by pontusmelke** [comment]
- Moved stuff out of 2.3
- Renamed `CompiledNode` to `NodeIdWrapper`, likewise for relationships

**Pull request merged**
