### PR TITLE
Remove several deprecations

### PR DESCRIPTION
**Pull request by davidegrohmann**

### CODE REVIEW

**Comment by systay** [comment]
Awesome!

**Comment by chrisvest** [comment]
@davidegrohmann First review round done. I had some comments. Looks like you also need to add some exceptions to clirr.

**Comment by davidegrohmann** [comment]
@chrisvest yes I am fighting with clirr right now

**Comment by chrisvest** [comment]
@davidegrohmann Needs a rebase

**Comment by chrisvest** [comment]
@davidegrohmann The reintroduced `org.neo4j.function.Supplier` has a wrong license header.

**Comment by chrisvest** [comment]
@davidegrohmann And it needs another rebase.

**Pull request merged**
