### PR TITLE
Moving bolt_advertised_address into the server module for use in discovery

### PR DESCRIPTION
**Pull request by mneedham**
(requested by drivers team)

### CODE REVIEW

**Comment by apcj** [comment]
Needs a rebase now, sorry @mneedham

**Comment by mneedham** [comment]
Will do that in the morning. It was failing with a bunch of errors on the
PR build before. Not sure whether this commit caused that or there was some
flakiness elsewhere.

**Comment by mneedham** [comment]
Ok have rebased. Let's see how it fares this time.

**Comment by mneedham** [comment]
@apcj  I can't figure out what I've done wrong here but the EdgeServerReplicationITs are still failing. I tried moving the setting + associated functions/classes into neo4j-server from scratch again and the tests are still failing but they work without the change.

Must be missing something obvious but I'm not sure what!

**Pull request closed without merging**
