### PR TITLE
[tls] disable client-initiated renegotiation

### PR DESCRIPTION
**Pull request by martinfurmanski**
Client-initiated renegotiation is a possible source for DDoS.

### CODE REVIEW

**Review by andrewkerr9000 — APPROVED** [review]
LGTM

This is not a well documented setting...
https://bugs.openjdk.java.net/browse/JDK-8073643

**Comment by chrisvest** [comment]
I think it would be good to have comments above those lines that explain why that particular setting is a good idea.

**Comment by martinfurmanski** [comment]
@chrisvest Good enough?

**Comment by chrisvest** [comment]
@martinfurmanski Yes.

**Pull request merged**
