### PR TITLE
Support different source compilers

### PR DESCRIPTION
**Pull request by thobe**
Adds configuration options for the SourceCode code generation strategy for configuring which compiler to use for compiling the source code.

Moves class templates to better places in the code.

Also introduces a flag for simplifying try-with-resource blocks to try/finally-blocks.

### CODE REVIEW

**Comment by thobe** [comment]
Supersedes #4868

**Comment by lutovich** [comment]
@thobe would we really need support for multiple compilers? Bytecode generation was accepted as a way to go and this change does not confirm with it.

**Comment by thobe** [comment]
@lutovich: No. And the main part of multiple different compilers has been removed from this PR (it was in #4868), it just kept that name... What remains are some refactorings, and I think those are sensible. Perhaps I should change the commit message.

**Comment by systay** [comment]
Please re-open when you are ready to merge this in, @thobe

**Pull request closed without merging**
