### PR TITLE
Add some slack in update puller thread observations in UpdatePullerSwitchIT

### PR DESCRIPTION
**Pull request by chrisvest**
This way, we don't require that the update puller threads start and stop immediately, but rather allow them some time to start and stop.
This is necessary because we only cancel the update puller scheduler on a slave when we switch to master; don't wait for the update puller thread to terminate.
This is the race that we were seeing, and this 2 second grace period in the test should make it much more unlikely to fail.

### CODE REVIEW

**Comment by lutovich** [comment]
Slave update pulling consist of two thread. First is a recurring job started by `UpdatePullerScheduler`, this thread does no actual pulling, it just pokes the other thread and it's name always remains unchanged. Second thread is started by `SlaveUpdatePuller` and it pulls updates, it's name is set to `UpdatePuller@X`. There exists a latch in `SlaveUpdatePuller#shutdown()` which is released only when name of this thread is set back to normal. So mode switch for slave should always finish only after name is reset. This is why I do not quite understand the explanation for this change.

**Comment by chrisvest** [comment]
Yes, the explanation is wrong as you observe. I also don't know if this actually fixes anything, because I couldn't get the test to fail locally after 1200 tries. Not sure what the failure frequency is on CI.

**Comment by tinwelint** [comment]
It looks like this test fails a couple of times a day, so the feedback loop should be quick

**Comment by lutovich** [comment]
Closing this PR for now. Thread in `SlaveUpdatePuller` should be stopped and not visible after `#shutdown()` because of the latch. We need to understand how thread with `UpdatePuller@X` prefix still remains visible.

**Pull request closed without merging**
