### PR TITLE
Correct description of `dbms.security.ha_status_auth_enabled`

### PR DESCRIPTION
**Pull request by cleishm**

### CODE REVIEW

**Comment by tinwelint** [comment]
Please rebase, there were recently introduced problems in the 2.3 build, which I believe have been reverted now.

**Comment by tinwelint** [comment]
Or, better yet, just merge straight in. No reason to create a pull request for a thing like this is there? For the sake of reviewing? Meh, ask someone instead.

**Comment by cleishm** [comment]
@tinwelint: I treat my contributions as "community", so a PR is essential.

**Comment by cleishm** [comment]
PS. Thanks for the review/merge!

**Pull request merged**
