### PR TITLE
Improvements to stopping Neo4j

### PR DESCRIPTION
**Pull request by benbc**

### CODE REVIEW

**Comment by spacecowboy** [comment]
Question @srbaker @benbc , why do we even have this service script anymore? Why do we not only have a SystemD unit?

Would probably remove some issues as we could simply run neo4j in the foreground in that unit. Something like

```
[Unit]
Description=Neo4j

[Service]
User=neo4j
ExecStart=/usr/bin/neo4j console
LimitNOFILE=40000

[Install]
WantedBy=multi-user.target
```

**Comment by benbc** [comment]
@spacecowboy The current LTS versions of Debian and Ubuntu don't use SystemD.

**Comment by benbc** [comment]
(But you are right that switching to it would solve various problems. It's something I'd like to do.)

**Comment by spacecowboy** [comment]
Right, that makes sense.

**Pull request merged**
