### PR TITLE
Improve parameterized test names

### PR DESCRIPTION
**Pull request by benbc**

### CODE REVIEW

**Comment by thobe** [comment]
@benbc can't make up your mind on how you want this to behave can you?
This version looks good to me as well.

**Comment by benbc** [comment]
@thobe Indeed. I foolishly failed to check whether this was already fixed in later branches. Once I tried the merge it became obvious. I thought for everyone's sanity it would be better if it's the same everywhere.

**Comment by thobe** [comment]
heh... just like I foolishly failed to check which branch you were targeting with this change...

**Comment by benbc** [comment]
Well, I didn't like to say anything.

**Pull request merged**
