### PR TITLE
New feature: support reading/writing blobs in Neo4j

### PR DESCRIPTION
**Pull request by bluejoe2008**
I created a neo4j-blob module in project and modified some related existing modules (kernel, values ...) to make it possible and convenient to store and use the BLOB in neo4j database.

https://github.com/bluejoe2008/neo4j-blob/tree/blob-support/community/neo4j-blob describes how to handle BLOBs in Neo4j database. Unlike `byte arrays`, BLOBs represent binary streams stored in an EXTERNAL storage (local files system, distributed file system, etc) and can be consumed in a streaming manner (only offer new bytes on calling `next()`).

I hope this feature is accepted by you and this helps people able to store structured data and unstructured data in ONE database.

### CODE REVIEW

**Comment by bluejoe2008** [comment]
I sent 2 mails to cla@neotechnology.com but got no reply.
Is that mail box keep working?

**Comment by thobe** [comment]
@bluejoe2008 Both emails have been received. I am sorry nobody reconnected with you. I will look over our processes around this.

I notice that there are contributions from two accounts here. There are CLA agreements received from both of them.

**Comment by bluejoe2008** [comment]
Glad to know that all checks have passed, thank @thobe 
What should we do while waiting for this pull request to be accepted/denied?

**Comment by technige** [comment]
Hi @bluejoe2008 

Thank you very much for your suggestion and for spending what has clearly been a large amount of time working on your feature request. Unfortunately, despite this clear huge effort, we're unable to accept the code, since there are considerably more layers of the system to take into account, beyond the ones you have looked at. Furthermore, a type system change such as this is _so_ significant, that it would need to be part of our formal product roadmap, and built in a co-ordinated fashion in-house.

In terms of BLOB itself, this data type would not only have significant implications on data transfer (server-to-server, client-to-server, etc) and data storage layers, but also on _how_ people approach data modelling with Neo4j in general. Storing large amounts of data in a single property would indeed affect the design of our entire product and peripheral tooling, such as visualisation apps.

All of that said though, we have had a number of discussions over the past few years about implementing BLOBs. This is very likely to become part of the product at some point, but I'm unable to give you any concrete timeline. In the meantime, I would suggest using the byte array type instead, along with metadata in associated properties (if required).

Thank you again for the work that you put in here, and sorry that we are unable to accept it.

**Comment by bluejoe2008** [comment]
ok,fine
it is really a pity :(
thank you for your reply!

**Pull request closed without merging**
