### PR TITLE
Restructure Cypher compiler code

### PR DESCRIPTION
**Pull request by systay**
This is an attempt to separate out the more semantical parts of the 
compiler into its own module. The new `frontend` module contains
the parts usually called the front end of a traditional compiler:

> The compiler frontend analyzes the source code to build an internal representation of the program, called the intermediate representation or IR. It also manages the symbol table, a data structure mapping each symbol in the source code to associated information such as location, type and scope.

So parsing, the AST, semantic checking and the produced semantic table containing
type information about identifiers and expressions is all in this module.

### CODE REVIEW

**Comment by thobe** [comment]
Looks like a good start. But I'm not convinced that `cypher-semantic` is the right name.

I also wonder if we should wait with merging until this change is "more complete".

**Comment by systay** [comment]
+1 on `cypher-semantic` not being the best name. Open for suggestions
I rather not wait more than necessary with merging it, unless there is something we should fix. Afraid of the rebase cost

**Comment by thobe** [comment]
@systay how about `cypher/frontend`, then it feels about ready to merge now.

**Comment by systay** [comment]
:+1:

**Pull request merged**
