### PR TITLE
Use MANIFEST.MF to determine kernel version.

### PR DESCRIPTION
**Pull request by jakewins**
- First step towards removing code generation of ComponentVersion.

### CODE REVIEW

**Comment by jakewins** [comment]
This is gonna need some work. There's a lot of usages of this, and the PR as it stands does not satisfy them properly. Some things noted:
- We need a "clean" version, for public display in UIs (2.0.0-M01)
- We need a "detail" version that can be traced to a git revision (2.0.0-M01-abcdefg)
- We currently keep a version with most jars we generate, and print that out on startup, to verify users have not mixed incompatible versions. I'd love to avoid having code generation or a required pom entry (for the MANIFEST package name) in each pom.

The last one - is it really necessary? We already print the directory structure on startup, which contains the jar files, which all have their versions in their names.

**Comment by benbc** [comment]
@jakewins This is great. I STRONGLY SUPPORT your efforts here.

Can I check that I understand what you are doing with git Git SHA? I think you are hacking the `Implementation-Version` to use it as a general-purpose metadata store. Is that right: you're not (at this point) changing the product's "official" version string to include the SHA and the "detail" version is completely internal to the jars?

If that's your intention, can I suggest that you use a separator that's guaranteed not to appear in the version string (instead of a hyphen)? Just to ease parsing and the possibility of easy extension later. Comma, maybe?

I plan to improve traceability at some point by enhancing the official version number to include a build-unique component. But that will need to be integrated in a way that's consistent with semver and needs to consider the needs of the whole build pipeline.

**Comment by jakewins** [comment]
+1 on all the things, I'll change it to a comma

**Comment by jakewins** [comment]
I think I've addressed my own concerns here so far at least. This commit leaves cleanup to be done of all the ComponentVersion code, but I think that can be done in a follow-up commit.

What this needs though is validation that this is not interfering with UDC and that versions look proper. I've manually validated that the version in the browser and the one in JMX looks sane. I'm not sure how to test UDC.

It's a bit tricky, since the version is only available if you're running with the kernel in its jar, which intellij does not do..

**Comment by benbc** [comment]
@jakewins You don't seem to have removed the code-generation-related stuff.

**Comment by benbc** [comment]
@jakewins For testing UDC build a complete package (e.g. the tarball). Stand up any old web server and turn on request logging. Configure Neo4j from the tarball to point to your web server as its UDC server. Examine the request logs.

**Comment by thobe** [comment]
Before we had `ComponentVersion`, we tried this approach. I don't remember why we abandoned it. It could have been one or several of these reasons:
- Testing purposes. The `MANIFEST.MF` information did not get generated or picked up until everything was packaged into a jar-file, and maven insists on running unit tests against class-files in a classes directory, rather than on a packaged jar-file.
- Discoverability purposes. In order to log the version of each Neo4j component we need to discover which components were present, so we used ServiceLoader with generated classes to do that. The reason for wanting to do this was because we wanted to be able to see from the logs if there could be issues with incompatible versions of components being used. This was important back in the day when we didn't distribute a packaged version of Neo4j, but users assembled their own set of Neo4j modules.

We actually didn't fully remove the use of `MANIFEST.MF`, the parent class of the `ComponentVersion` classes exposes that information as well.

All that said, and without having looked at the actual implementation in this PR, I'll say that I like the general approach here.

**Comment by jakewins** [comment]
@benbc updated to remove code generation, looks happy :)

**Comment by jotomo** [comment]
What's the trick for making IntelliJ happy while _ComponentVersion_ still exists (the generated class not being able to resolve kernel classes). And sorry for hijacking :-)

**Comment by jakewins** [comment]
@jotomo hitting merge on the PR! :) Seriously though, it's been a while since I had to resolve this last time.. There are a few levels to this - there's both annotation-based code generation to make ComponentVersion's loadable via java service loader, and there's the actual code generation itself and making intellij find that generated code.

The code is generated when you do a regular `mvn clean install -DskipTests`. That's step one - after that, you need to make sure intellij picks up on the generated code, it should, for the kernel module for instance, detect a generated source folder under `target/generated-sources/version`, and you'd need to add it if it does not find it.

Finally, to get the annotation processing to work, you need to turn on annotation processing in intellij for the project. I don't remember how to do that, but google will likely find it for you!

**Comment by jakewins** [comment]
@benbc I think so! The annotation-based generation is a separate framework which we use in many places where we have java services, so it doesn't change really, and this was the only place I coud see the generation mentioned.. Oh, although there are going to be projects with the "ignore" stuff added in their poms, I'll clear those out.

Re: patch-version; We still don't have a patch version for the snapshots, eg. the main branch currently has '2.3-SNAPSHOT' as its version. We'd need to change that first if we want to lock in having a patch version. This might be a good way to do that though - do I remember you saying this is simply a manual thing that gets set during releases?

I'd suggest we merge this PR as-is, after the little pom cleanup, follow up with a `s/2.3-SNAPSHOT/2.3.0-SNAPSHOT/g`, and then set things up to fail CI if we ever put in a version without a patch number again.

**Comment by benbc** [comment]
Sounds great. Feel free to merge yourself if the build goes green while I'm
asleep and you have itchy fingers.

**Comment by jakewins** [comment]
They itch terribly!

**Pull request merged**
