### PR TITLE
Replace chain of if with switch

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by remyleone** [comment]
I don't have credentials for accessing the Team City site

**Comment by MishaDemianenko** [comment]
Hi @sieben great; CI configuration was updated and as far as I can see you need to update code formatting according to our code style. You can verify that checkstyle is happy with your changes locally by running, for example, "mvn checkstyle:check"

**Comment by remyleone** [comment]
@MishaDemianenko the build sometimes fails for no clear reasons even during `mvn clean install` :/ Is there a way for me to connect to teamcity to see the errors?

```
[ERROR] Failed to execute goal on project neo4j-command-line: Could not resolve dependencies for project org.neo4j:neo4j-command-line:jar:3.4.0-SNAPSHOT: The following artifacts could not be resolved: org.neo4j:neo4j-kernel:jar:3.4.0-SNAPSHOT, org.neo4j:neo4j-kernel:jar:tests:3.4.0-SNAPSHOT: Could not find artifact org.neo4j:neo4j-kernel:jar:3.4.0-SNAPSHOT -> [Help 1]
```

**Comment by MishaDemianenko** [comment]
@sieben unfortunately, there is no way currently for external contributor to access TC directly

**Review by MishaDemianenko — APPROVED** [review]

**Comment by MishaDemianenko** [comment]
@sieben This PR is also approved and will be merged into 3.5 as part of https://github.com/neo4j/neo4j/pull/11758 since 3.4 switched to maintenance mode.
Thx for your contribution!

**Comment by MishaDemianenko** [comment]
Integrated into a product as part of https://github.com/neo4j/neo4j/pull/11758

**Pull request closed without merging**
