### PR TITLE
More clear names for page cache and page cursor tracers.

### PR DESCRIPTION
**Pull request by MishaDemianenko**

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@burqen / @tinwelint looks better now? 🦄

**Review by burqen — APPROVED** [review]
Much more clear 🤘

**Comment by tinwelint** [comment]
@MishaDemianenko still no javadoc on how each is used?

**Comment by MishaDemianenko** [comment]
@tinwelint add some java docs

**Pull request merged**
