### PR TITLE
Add enterprise neo4j-harness

### PR DESCRIPTION
**Pull request by FylmTM**
- Enterprise test server builders
- Enterprise Junit rule
- Basic tests to ensure that server is created

### CODE REVIEW

**Comment by nawroth** [comment]
I think there should be a separate test project just like with https://github.com/neo4j/neo4j/tree/2.3/manual/neo4j-harness-test so we're sure users end up with the right kind of test database and dependencies when using it.

**Comment by FylmTM** [comment]
@nawroth I should create `neo4j-harness-enterprise-test` module, with same content, adapted dependencies and proper test server builder?

**Comment by nawroth** [comment]
@FylmTM Yep, that would be great!

**Comment by cleishm** [comment]
This has some cross over with #4674, which should be reintroduced now that we're targeting PRs to 3.0

**Comment by jakewins** [comment]
Since we're not currently planning a new minor version release in the 2.x series, and we generally avoid releasing new features in patch releases, I've retargeted this PR against 3.0 here: https://github.com/neo4j/neo4j/pull/5675/commits

@nawroth let me know if that look ok maven-wise to you, and I'm happy to merge it if that PR is green.

@FylmTM as always, super-duper appreciate your contributions!

**Comment by FylmTM** [comment]
@nawroth @jakewins I was a bit busy. I am going to add example project tomorrow and update PR :)

**Comment by jakewins** [comment]
Feel free to open a new PR against 3.0 if you want to add more things to
the commit, and I'll close the PR I just opened :)

**Pull request closed without merging**
