### PR TITLE
Return correct results for parameter maps in predicates

### LINKED ISSUE #1525: MATCH with properties inconsistency in REST API
Hi,
I was trying the new MATCH with properties cypher feature in Neo4j 2.0 RC1 using the REST API. 

I noticed that if I explicitly hard coded the properties in the cypher query it worked as expected. But I passed the properties as a parameter it doesn't work. This behaviour seems to be inconsistent with the way other cypher queries and params work.

A very basic program in Python to illustrate the issue and the output is [here](https://gist.github.com/ducky427/7579861).

### PR DESCRIPTION
**Pull request by sherfert**
changelog: Fixes #1525. Comparing nodes and relationships to maps
in predicates returns correct results now.

### CODE REVIEW

**Comment by pontusmelke** [comment]
I don't think it should allowed to do compare a node and map for equality

**Comment by systay** [comment]
I'm with @pontusmelke on this one. Don't see why we would want to do this.

**Comment by thobe** [comment]
This behaviour is **not** what was desired in #1525. The desired behaviour in that ticket it to be able to match using all properties (in the `allProps` map parameter) when using a query like this: `MATCH (n{allProps}) RETURN n`.

The behaviour implemented in this pull request is wrong, and in violation of the specification of `=`.

Since any change addressing #1525 will be substantially different from what is done here, and since what has been implemented here is not going to get merged, I'm closing this PR.

**Comment by craigtaverner** [comment]
The behaviour coded in this feature was decided on in a discussion between Tobias and Chris in https://github.com/neo4j/neo4j/pull/1542, not in #1525. The fact that this PR was associated with #1525 is misleading, as the desired behavior in that card was rejected in that card, but instead a discussion ensued in https://github.com/neo4j/neo4j/pull/1542 where the behaviour coded for this PR was in fact explicitly decided on by Tobias and Chris. Of course, that decision could be revoked.

**Pull request closed without merging**
