### PR TITLE
Fix store copy on block device

### PR DESCRIPTION
**Pull request by chrisvest**
This was broken by a forward merge of a fix of another issue.

### CODE REVIEW

**Comment by chrisvest** [comment]
Marking it as not ready for merge, because I don't think it currently moves anything _other_ than store files.

**Comment by chrisvest** [comment]
@burqen @mneedham @digitalstain This should make store copy work on block device storage _and_ preserve the behaviour modifications you introduced in 3.0. Please take a look.

**Comment by digitalstain** [comment]
I like this change, it fixes the known issues with the non default store copy strategy.

**Comment by chrisvest** [comment]
The build is finished, even though the status is still yellow on GitHub. Probably a missed notification of some sort.

**Review by burqen — APPROVED** [review]
LGTM
Really nice comments explaining the asymmetric usage of `FileMoveAction` between record files and other store files.

**Pull request merged**
