### PR TITLE
Fix cluster uri resolution

### PR DESCRIPTION
**Pull request by spacecowboy**
Reverts part of 5f7bf49d546e8b91aafa11e3df8938a42d305bf9

Reason:
When cluster members do not specify `ha.server` setting (not required),
the slaves are unable to join the cluster in certain cases.

### CODE REVIEW

**Comment by tinwelint** [comment]
Thinking that the behaviour that this PR aims to revert might be useful in some environments (multi-datacenter f.ex.), should we instead of reverting introduce another config option `ha.use_host_names` or whatever it would be called, where if `true` would expose the host name instead of the ip address. This setting could be `false` by default to simplify for the most common case. Sure there would be one more config option, but the amount of config user has to do to just get things going would be less. Not until you're doing serious clustering across data centers you'd have to care about this config and the `ha.server` setting.

**Comment by spacecowboy** [comment]
@tinwelint We shouldn't introduce new functionality in a patch release. I think it's better to try to fix the default behavior to take these changes into account.

**Comment by spacecowboy** [comment]
@tinwelint New suggested behavior pushed

**Comment by spacecowboy** [comment]
Tests show this is insufficient to fix connectivity in all network cases.

Edit: This actually fixes the regression. We have additional problems which will be addressed for 3.0

**Pull request merged**
