### PR TITLE
Cluster code no longer resolves hostnames into IPs.

### PR DESCRIPTION
**Pull request by rickardoberg**
More changes to allow cross-datacenter clusters.

### CODE REVIEW

**Comment by chrisvest** [comment]
@rickardoberg Testing?

**Comment by davidegrohmann** [comment]
@rickardoberg needs rebase

**Comment by davidegrohmann** [comment]
@rickardoberg this needs a rebase

**Comment by digitalstain** [comment]
@davidegrohmann rebased - should be merged on green build

**Pull request merged**
