### PR TITLE
Do not reply roles on cluster joins

### PR DESCRIPTION
**Pull request by davidegrohmann**

### CODE REVIEW

**Comment by tinwelint** [comment]
I see no reason to merge this unless you describe _why_ you're making this change, and _what_ the problem was. Changes to maintenance versions must be very well understood and tested.

**Comment by davidegrohmann** [comment]
@tinwelint this is the outcome of what I have agreed with @digitalstain yesterday. Specifically:
1) there are no tests describing how cluster joins work and he didn't remember either. That sad and given the fact that basically every single tests in HA test cluster joins we agreed that current test coverage is enough for this.
2) about _why_, we have seen an issue very likely caused by that "catch up with election" code, but we decided to not add that as part of the commit message since we are not 100% sure this is gonna fix it.

**Comment by MishaDemianenko** [comment]
Since there is not test at all affected, and we _not sure_ and _very likely_ and we do not have any new tests i fully agree with @tinwelint it should not go to 2.2.

**Comment by davidegrohmann** [comment]
@tinwelint @MishaDemianenko I leave the decision to @digitalstain. Are you suggesting we delete the flaky tests instead?

**Comment by tinwelint** [comment]
@davidegrohmann @digitalstain I'm suggesting that we understand this change before deciding to merge. I don't think that's unreasonable to ask, given this is aimed for 2.2.

**Comment by MishaDemianenko** [comment]
@davidegrohmann @digitalstain @tinwelint would suggest we do fix in 3.0 first, to see if our understanding of a problem is correct and we do not brake anything else, having a test case as part of pr will also help (or name of a test that we are trying to fix mentioned somewhere). 
Then we can decide do we need to touch production branch and merge fix down.

**Pull request closed without merging**
