### PR TITLE
Add Cypher compiler performance testing and optimization and make getDegreeOptimizer rewrite size(...) expressions

### PR DESCRIPTION
**Pull request by boggle**

### CODE REVIEW

**Comment by davidegrohmann** [comment]
@boggle why is this PR now a big mix of commits instead of `CypherCompilerPerformanceTest` related only?

**Comment by boggle** [comment]
All those commits are at least tangentially related to working on compiler performance w the exception of getdegree work which was an omission from yesterday

**Comment by davidegrohmann** [comment]
@boggle Fair enough. Perhaps update title and description PR accordingly?

**Comment by boggle** [comment]
@davidegrohmann Good call. Done.

**Pull request merged**
