### PR TITLE
3.0 desktop scripts fixes

### PR DESCRIPTION
**Pull request by benbc**

### CODE REVIEW

**Comment by benbc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HX3JPSKk&#x2F;20-command-line-tools-do-not-seem-to-work"> Command-line Tools do not seem to work</a>

**Comment by benbc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ElJkWoP5&#x2F;13-neo4j-shell-problem-in-osx-desktop-app"> Neo4j-shell problem in OSX Desktop app</a>

**Comment by systay** [comment]
@benbc Any progress on this?

**Comment by benbc** [comment]
This was addressed by removing the terminal launcher from Desktop. Closing this PR.

**Pull request closed without merging**
