### PR TITLE
Remove system/lib

### PR DESCRIPTION
**Pull request by srbaker**

### CODE REVIEW

**Comment by srbaker** [comment]
I need someone to look at 7d018b465585f20e8a06513f41a9100315629a2f specifically and tell me how to squish that into _one_ dependencySet stanza. My Maven-fu is poor, and everything I've tried winds up causing issues.

**Comment by benbc** [comment]
@nawroth Do you have any idea about the problem @srbaker is having above?

**Comment by benbc** [comment]
@srbaker Can you get rid of the merge commit, please?

**Comment by benbc** [comment]
@srbaker Have you run the Windows stuff?

**Pull request merged**
