### PR TITLE
CSV path for metrics data defaults to store directory

### PR DESCRIPTION
**Pull request by tinwelint**
That setting was using a deprecated and unused "store_dir" setting
function. Now uses KernelContext instead. Added common utility for
getting absolute/relative paths from config values.

### CODE REVIEW

**Comment by davidegrohmann** [comment]
Given the problem we had with `rrdb` files in the store directory. Is it possible to find a better default or perhaps not to have a default at all?

**Comment by tinwelint** [comment]
That's indeed a good point @davidegrohmann . Then removing default I think sounds better.

**Comment by tinwelint** [comment]
@davidegrohmann although what about current behaviour... this will be seen as a breaking change, even if the previous behaviour was broken as heck

**Comment by davidegrohmann** [comment]
@tinwelint isn't a broken default value a bug?

**Comment by MishaDemianenko** [comment]
@tinwelint will agree with @davidegrohmann it looks putting metrics into store folder does not sounds like a good idea. Can we move it somewhere else? New folder as example?

**Comment by tinwelint** [comment]
Although a file simply living in the store directory _shouldn't_ cause problems, because we only move/delete a select set of files in there. Anyways. Removing the default is good enough for now I think.

**Comment by tinwelint** [comment]
@davidegrohmann removed the default, but kept the ability to provide relative path anyway. Reasoning is that even if we only supported absolute path the user could still specify the store directory as absolute path. Would we then actively prevent the config to point to a location under store directory? That might be taking things too far. This might be a good balance.

**Comment by thobe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4P7wyz7w&#x2F;1639-metrics-csv-path-setting-was-designed-to-default-to-storedir-metrics-csv-but-doesn-t"> metrics.csv.path setting was designed to default to storeDir&#x2F;metrics.csv, but doesn&#39;t</a>

**Comment by davidegrohmann** [comment]
@tinwelint I am fine with your solution. Still quite a bit of tests to be fixed.

**Comment by tinwelint** [comment]
@davidegrohmann green

**Pull request merged**
