### PR TITLE
:help for new Cypher commands.

### PR DESCRIPTION
**Pull request by oskarhane**

### CODE REVIEW

**Comment by pe4cey** [comment]
Do we want the code snippets to be runnable?

**Comment by oskarhane** [comment]
@pe4cey Maybe add a warning to the `DETACH DELETE` slide?

**Comment by pe4cey** [comment]
@oskarhane I would vote to make these destructive cypher queries not clickable in the ui. I see these examples looking like the example in :help cypher (first slide)

**Comment by oskarhane** [comment]
There's only one destructive added, but sure, let's make it non-clickable.

**Pull request merged**
