### PR TITLE
Added retry block when a deadlock detected by Forseti to reduce false positive deadlocks

### PR DESCRIPTION
**Pull request by zhenlineo**
This pr could drop the product performance when there is a real deadlock. However it will not
harm but improve the success rate when false deadlock detected.

### CODE REVIEW

**Comment by davidegrohmann** [comment]
@zhenlineo maybe we should test if your change will actually improve the situation

**Comment by zhenlineo** [comment]
@davidegrohmann That's why it is "not ready for merge" :)

**Comment by cdshines** [comment]
I'm doing the same in my project and from my experience, it's rarely a reasonable idea to retry immediately after the deadlock is detected (and in case of external (relatively to kernel) control the pause between attempts is (maybe not much) a little longer). I started with 12 to 24 retries in various places over the system and the only thing I managed to get was just a longer list of interlocked transactions. I introduced timeouts for the upper 1/4-1/5 of attempts and that helped, but is that a good design choice? I'm not sure. Maybe this kind of fail-fast behavior is better for the kernel and API users like me should bear the burden of recovery by themselves?

But in case this works it will be probably the most appreciated feature from my POV :)

**Comment by thobe** [comment]
@cdshines This is not about retrying when an actual deadlock is detected. At this level that would not solve anything, because no locks would be released. This is in order to compensate for a deadlock detection algorithm that yields false positives.

I still think that this is the wrong way to solve this. If we know that our detection algorithm yields false positives, we should do a full check when it reports a deadlock. I.e. still construct a lock acquisition graph like we used to do with the old lock manager, but use the fast deadlock detection of `Forseti`. In the case where `Forseti` reports a deadlock we should run through the lock acquisition graph and verify that deadlock, and actually continue if it turns out `Forseti` was wrong. But perhaps there are reasons I'm unaware of why such an approach would not be possible.

**Comment by zhenlineo** [comment]
@cdshines We finally managed to make the false positive dead lock less often by adding retries and modifying SimpleBitSet Map to use optimistic locks. However if we do so, the performance is largely affected. We are discussing about new lock managers right now. But before we got a new lock manager, if you found the false positive deadlocks were too open to tolerance, I suggest you to try Community lock manager. You will find how to use that in class `ForsetiServiceLoadingTest`.

**Pull request closed without merging**
