### PR TITLE
Move property cursor APIs to the OperationsFacade

### PR DESCRIPTION
**Pull request by davidegrohmann**
Builds on top of #8792

### CODE REVIEW

**Comment by tinwelint** [comment]
I think this looks good. Just thinking, it changes execution path for e.g. getting a property from:

- Down through kernel cake layers
- Get/construct NodeItem and cursor
- Up through kernel cake layers
- Get/construct property cursor from NodeItem

to:
- Down through kernel cake layers
- Get/construct NodeItem and cursor
- Up through kernel cake layers
- Down through kernel cake layers <--
- Get/construct property cursor from NodeItem
- Down through kernel cake layers <--

Doesn't it? Would, as always, be great to measure before merging because these are super hot paths.

**Comment by tinwelint** [comment]
@davidegrohmann this can now be rebased since #8792  has been merged

**Comment by davidegrohmann** [comment]
@tinwelint rebased

**Comment by davidegrohmann** [comment]
@tinwelint rebased again :)

**Comment by tinwelint** [comment]
@davidegrohmann I triggered a JMH run, also please rebase once more

**Comment by davidegrohmann** [comment]
@tinwelint I have run jmh already and I send you the results as well for this branch.

**Comment by tinwelint** [comment]
oh, right so you did, all good then

**Comment by davidegrohmann** [comment]
@tinwelint are you ok with merging this PR?

**Pull request merged**
