### PR TITLE
Support of log level setting in server and extension loggers.

### PR DESCRIPTION
**Pull request by MishaDemianenko**
Support log level defined in store_internal_log_level setting
for server and extensions loggers

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
@benbc can you please take a look, thx

**Comment by benbc** [comment]
@MishaDemianenko I think there is a further step needed here.

`Config` provides a mechanism for changing the logger after instantiation for exactly this reason -- so that logging can be configurable but configuration still have access to a logger. Look inside `Config` at the references to `bufferedLog` and see how it's used.

So you should avoid creating that `configLog` and allow it to use the temporary buffer instead. Then once you have created the actual log (now depending on configuration) you can call `Config#setLogger`. But this means that all clients of `ConfigLoader` will need to change, to set the logger themselves rather than passing it in.

It's a question of making server follow the same pattern that kernel does.

I have a wider ambition here to stop creating the `Config` object in two places (in server and kernel), which will simplify this because we'll have to do the log/config dance in only one place. But I think that's out of scope for what you're doing now.

**Comment by benbc** [comment]
@MishaDemianenko PS I'm figuring this out as I go along, so please tell me if my analysis is wrong.

**Comment by MishaDemianenko** [comment]
@benbc nice buffering log :) didn't know we have that, thx.
Code has been updated to avoid separate logger creation for config construction. 
To be able to do so i update config loader and config construction. 
I think now it's a bit more complex comparing with first solution, but if you prefer this variant i'm fine with it.

**Comment by benbc** [comment]
@MishaDemianenko This looks fine to me. Thanks.

**Comment by MishaDemianenko** [comment]
@benbc can we merge this?

**Comment by benbc** [comment]
@MishaDemianenko Yes! That was my intention with my last comment.

**Comment by spacecowboy** [comment]
@MishaDemianenko Just in case you forgot, this appears to be good to merge

**Pull request merged**
