### PR TITLE
Dumb down the page cache settings, and fix the default dbms.pagecache.memory setting at 2 GiB

### PR DESCRIPTION
**Pull request by chrisvest**
Also fix many tests, so they use DatabaseRule or TestGraphDatabaseFactory and the like, which changes the default page cache size to 8 mega-bytes for the purpose of testing.

### CODE REVIEW

**Comment by chrisvest** [comment]
We should probably also update the docs so it becomes clear to anyone who installs neo4j for the first time, that they probably want to change the `dbms.pagecache.memory` setting to something that suits their environment and load patterns better.

**Comment by tinwelint** [comment]
Out of curiousity, why default to a fixed value like that? Why not default to a percentace of total RAM on the machine or something?

**Comment by maxdemarzi** [comment]
I'm confused about this too... it's been 50% for 4 milestones and now we're defaulting to 2GB? I liked it at 50%, why the change?

**Comment by chrisvest** [comment]
@tinwelint @maxdemarzi The previous code failed to reliably figure out what "50%" meant, and often concluded that it meant "32 MiB" regardless of how much RAM you had. We discussed (and it's still up for discussion) using `(RAM - Heap) * 0.75` as the default, and then otherwise only allowing fixed sizes to be specified. Trouble is that the heap size might (very likely) change after we measure it during startup, plus figuring out how much RAM the system has is fiddly in Java, and it might fail. A fixed default is also easier to explain to those who install and configure it.

**Comment by tinwelint** [comment]
I think that answers my question, thanks

**Comment by thobe** [comment]
Since there are two changes here (1. changing the configuration of `dbms.pagecache.memory`, and 2. making use of `DatabaseRule` and `TestGraphDatabaseFactory`), can we please split those out into separate commits. Preferably into separate pull requests.

**Comment by chrisvest** [comment]
We can do that.

**Comment by chrisvest** [comment]
With a bit of luck, I might also be able to base the test changes on top of #4075. The configuration changes have to be based on top of the test changes, though.

**Pull request closed without merging**
