### PR TITLE
Created a Powershell Module to manage a Neo4j Server

### PR DESCRIPTION
**Pull request by glennsarti**
Added Powershell Module, called Neo4j-Management, to manage a Neo4j server on Windows platform
Added initial set of Pester based unit tests for the Powershell Module at 'packaging/standalone/src/tests'
Modified the existing Windows batch files to call the powershell module
Modified the Windows distribution files to include the powershell files
Modified the Unix distribution files to exclude the powershell files

### CODE REVIEW

**Comment by glennsarti** [comment]
Can I have please more information about which unit tests etc failed in the TC job.

**Comment by chrisvest** [comment]
It's apparently complaining about `/packaging/standalone/src/main/distribution/shell-scripts/bin/Neo4j-Management/neo4j-default-settings.xml` missing a license header. Not sure what header it wants, but `mvn license:format` should fix it.

**Comment by glennsarti** [comment]
Thanks @chrisvest .  I've updated the XML file.

**Comment by benbc** [comment]
cc @lassewesth

**Comment by benbc** [comment]
Right, I'm done, @glennsarti. Despite the avalanche of comments, this looks really good. I can't tell you how happy it makes me to see those batch scripts deleted.

**Comment by glennsarti** [comment]
@benbc "Could we have an arrangement where, by default, we just start with the properties file that is shipped in the zip archive?"

Ok, I'll review all of the settings I've added and only keep the ones that are set explicitly in the config files.

**Comment by benbc** [comment]
I mean not have an XML file at all. Can we not just use the properties
files? I think you may have explained this to me before, but I have
forgotten why the XML file is necessary.

**Comment by glennsarti** [comment]
The thinking was that the powershell module can be used to manage down-level neo4j instances e.g. the module from 2.3 server can be used to manage a 2.2 server.  The default settings are used to make these properties more visible to admins.  In the current properties file this is done using comments.

I use XML because windows always has an XML parser available.  JSON is only available in v3 and above.  I can remove the XML reading part of Get-Neo4jSetting and the rest of the code will be fine.

As an admin, is there any central place where I can find out what a default value is?

**Comment by benbc** [comment]
I think the duplicated default config in XML is a big risk. Perhaps we could drop the "manage other versions" feature for now and prioritize that separately; if we decide that it's important then we'll have to come up with a good way of mitigating the risk. @akollegger What do you think?

**Comment by glennsarti** [comment]
@benbc RE: Default XML file.  If we do decide to drop that feature, it's not a big code change.  I'll leave in the `IsDefault` property for the Setting object but it will always be set to False.

**Comment by jexp** [comment]
@benbc @glennsarti what's the current state of your work here? I thought it was already merged in :)

**Comment by glennsarti** [comment]
@jexp @benbc I've addressed all of the issues except for what to put in the batch files.  There was an outstanding question for @akollegger.  I haven't committed the changes yet as I was waiting on this to be resolved.  In the interest of time, I think I will reinstate the original batch files so at least the powershell code can be used, but it will not be the "default" method.

**Comment by glennsarti** [comment]
Updated all source code as per PR comments

**Comment by akollegger** [comment]
About "managing multiple versions" can we drop that for now? We can be more clever and awesome later on.

**Comment by glennsarti** [comment]
@akollegger  This has been done.  The default settings file for different Neo versions has been removed and the code to read that file has also been removed.

**Pull request merged**
