### PR TITLE
Remove remnants of ComponentVersion

### PR DESCRIPTION
**Pull request by chrisvest**

### CODE REVIEW

**Comment by burqen** [comment]
Looks like `Version.getRevision()` is not used any more after removal of `ComponentVersion.tmpl`.
I think it makes sense to clean that up in this commit as well.

**Comment by burqen** [comment]
@chrisvest First round finished. One small comment, otherwise nice.

**Comment by chrisvest** [comment]
@burqen `Version.getRevision()` is at least used in our RR builds.

**Comment by burqen** [comment]
@chrisvest Merging

**Pull request merged**
