### PR TITLE
Fixes an off-by-one length calculation for array types in InputCache

### PR DESCRIPTION
**Pull request by tinwelint**

### CODE REVIEW

**Review by chrisvest — COMMENTED** [review]
Why are there no tests catching this?

**Comment by chrisvest** [comment]
Also, a rebase should fix the tools compilation failure.

**Review by ragadeeshu — CHANGES_REQUESTED** [review]
I expected to see some test to go with this :)

**Comment by tinwelint** [comment]
The randomized InputCacheTest is showing this. You're right I should add a specific test for this.

**Pull request closed without merging**
