### PR TITLE
Modify nodes and rels to use idstructs rather than raw text.

### PR DESCRIPTION
**Pull request by jakewins**
While this adds a two-byte overhead for each id, the intent here is that identities would be represented the same way inside other structures as if they are stand-alone (eg. `RETURN id(n)`).

### CODE REVIEW

**Comment by jexp** [comment]
Would that affect `WHERE id(n) = 124` ?

**Comment by jakewins** [comment]
@jexp no :) But it's a good point, this doesn't deal with id() at all yet, just prep work for having the client tell when it gets an id back. Still need to figure what to do with id(), need to talk to @systay and friends..

**Comment by cleishm** [comment]
`id(n)` currently returns a (long) integer. If there's to be a non-integer type for ids, that needs to change also.

**Comment by jakewins** [comment]
@cleishm true. And we should probably sort that out via a CIP before merging this, closing for now.. To be continued!

**Pull request closed without merging**
