### PR TITLE
Remove useless semi-colon

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by remyleone** [comment]
I don't have credentials for accessing the Team City site

**Comment by MishaDemianenko** [comment]
Hi @sieben 
Thank you for your contribution!
To be able to merge your changes we will need a signed CLA from you.

See http://neo4j.com/developer/cla/ for further information.
Additional information on contributing code can be found at
http://neo4j.com/developer/contributing-code/

**Comment by remyleone** [comment]
I've sent the cla through mail.

Le lun. 30 avr. 2018 à 11:39, MishaDemianenko <notifications@github.com> a
écrit :

**Comment by MishaDemianenko** [comment]
Hi @sieben great; CI configuration was updated and as far as I can see you need to update code formatting according to our code style. You can verify that checkstyle is happy with your changes locally by running, for example, "mvn checkstyle:check"

**Comment by remyleone** [comment]
@MishaDemianenko I think it's fixed now :)

**Comment by MishaDemianenko** [comment]
@sieben yes its fine, thx for your contribution!
Only one thing, I will rebase your changes on top of latest 3.5 since 3.4 branch is in a maintenance mode and will gonna merge them as part of https://github.com/neo4j/neo4j/pull/11755

**Comment by remyleone** [comment]
No problem 😊

Em qui, 10 de mai de 2018 16:57, MishaDemianenko <notifications@github.com>
escreveu:

**Comment by MishaDemianenko** [comment]
Closed by https://github.com/neo4j/neo4j/pull/11755

**Pull request closed without merging**
