### PR TITLE
fix #12207 NullPointerException in ChunkedOutput.close() 

### LINKED ISSUE #12207: NullPointerException in org.neo4j.bolt.v1.transport.ChunkedOutput.close(ChunkedOutput.java:231)
https://github.com/neo4j/neo4j/blob/4a8518da491df99ca31fb48b76210a042693c67c/community/bolt/src/main/java/org/neo4j/bolt/v1/transport/ChunkedOutput.java#L228-L233

#### Stacktrace

```
2019-04-30 20:35:04.935+0000 ERROR [o.n.b.r.DefaultBoltConnection] Unable to close pack output of bolt session 'bolt-181'.
java.lang.NullPointerException
        at org.neo4j.bolt.v1.transport.ChunkedOutput.close(ChunkedOutput.java:231)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.close(DefaultBoltConnection.java:313)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:242)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Version

```console
$ curl -s http://localhost:7474/db/manage/server/version
{
  "edition" : "community",
  "version" : "3.5.5"
}
```

### PR DESCRIPTION
**Pull request by rmetzler**
fix #12207

### CODE REVIEW

**Comment by rmetzler** [comment]
I sent two emails to cla@neotechnology.com

**Comment by klaren** [comment]
CLA is received. For some strange reason, this PR does not contain author information in the GitHub API that we use. https://api.github.com/repos/neo4j/neo4j/pulls/12208/commits returns `author: null` so PR tests do not go green. I'll report this to GitHub...

**Review by lutovich — APPROVED** [review]
Looks good to me. Thanks @rmetzler!

**Comment by lutovich** [comment]
@rmetzler, just out of curiosity, do you know a way to reproduce this problem or you've just noticed a stacktrace in the log?

**Comment by rmetzler** [comment]
> @rmetzler, just out of curiosity, do you know a way to reproduce this problem or you've just noticed a stacktrace in the log?

I just noticed a stacktrace in the log. I was thinking about trying to reproduce the error using a mock, but I don't write much Java these days...

**Pull request closed without merging**
