### PR TITLE
Upgrade the git-commit-id-plugin to 2.2.0 from 2.1.13

### PR DESCRIPTION
**Pull request by chrisvest**
This should fix recent build failures on OS X

### CODE REVIEW

**Comment by spacecowboy** [comment]
Failed with: `the plugin pl.project13.maven:git-commit-id-plugin:2.2.0 requires Maven version [3.1.1,)`

**Comment by tinwelint** [comment]
@benbc @lassewesth Can we upgrade maven on our build agents to support this version of the plugin?

**Comment by lassewesth** [comment]
No. Stop using a dependency on Git to get the commit id (and thus tying our compile+test infrastructure to external, unrelated things).

Instead, have it delivered from CI where is it available from environment variables, and mangle the value into place that way.

**Comment by spacecowboy** [comment]
That sounds like a great idea. Then we can remove the plugin altogether.

**Comment by chrisvest** [comment]
@lassewesth Sounds like a good idea

**Comment by chrisvest** [comment]
Issued against wrong branch

**Pull request closed without merging**
