### PR TITLE
Skip shell tests when all tests are skipped.

### PR DESCRIPTION
**Pull request by MishaDemianenko**
@benbc or @spacecowboy can you please take a look.

### CODE REVIEW

**Comment by spacecowboy** [comment]
Tested it locally and it seems to work fine. @benbc will be happy that you managed to solve this

**Comment by spacecowboy** [comment]
@MishaDemianenko shall I do the merge when the time comes?

**Comment by MishaDemianenko** [comment]
@spacecowboy you can do that for sure or just let me know when i can do that :)

**Comment by spacecowboy** [comment]
@MishaDemianenko hmm, should it not be done against 3.0 perhaps?

**Comment by MishaDemianenko** [comment]
@spacecowboy since it's not a bug fix i just put it into last active branch, if you want i can reopen it against 3.0 ?

**Comment by spacecowboy** [comment]
@MishaDemianenko no, I just figured we might want to be able to skip them on 3.0 as well. no strong opinons either way

**Comment by benbc** [comment]
Thanks Misha.

**Pull request merged**
