### PR TITLE
Upgrade Scala to latest patch release

### PR DESCRIPTION
**Pull request by jotomo**
From 2.11.6 to 2.11.7.
Announcement: http://www.scala-lang.org/news/2.11.7

### CODE REVIEW

**Comment by systay** [comment]
@boggle Could you please check and merge if you are happy?

**Comment by boggle** [comment]
I'll take care of it.

**Comment by jotomo** [comment]
@boggle From the four known issues, the third, _Transient lazy vals should not null out fields and NPE_ https://issues.scala-lang.org/browse/SI-9365 has no impact (no (at)transient in the codebase). However, I saw a warning about unreachable code in pattern matching in internal/CypherCompiler:80 https://issues.scala-lang.org/browse/SI-9369. I think I attributed that to my IntelliJ set at the time.
The general idea of the PR being to get fixed issues in Scala in, of course.

**Comment by jotomo** [comment]
@boggle Scratch that comment about _unreachable code_, I got 2.2 & 2.3 mixed up.

**Comment by jotomo** [comment]
@boggle I just remembered that the 2.2 is independent of the 2.3 brach, so there's no need to wait for or do a forward merge. In 2.3, a POM variable _scala.version_ is defined in 4 POM modules, which needs updating. Should I take a look or is it quicker anyways if you do it?

**Comment by boggle** [comment]
@jotomo Thank you

**Pull request merged**
