### PR TITLE
Replace uses of org.neo4j.helpers.Clock with java.time.Clock.

### PR DESCRIPTION
**Pull request by apcj**
In module core-edge.

### CODE REVIEW

**Comment by lutovich** [comment]
Imo `java.time.Clock` interface is too wide for our needs. I do not really agree that our own `org.neo4j.helpers.Clock` should be deprecated and replaced with `java.time.Clock`.

**Comment by lutovich** [comment]
Please nvm me :)
Did not realize `java.time.Clock` contains many nice implementations like `FixedClock` and methods like `#tick()`.

**Comment by davidegrohmann** [comment]
@apcj to be moved to 3.1?

**Comment by apcj** [comment]
@davidegrohmann really thought I'd merged this - sorry! Will redirect to 3.1.

**Pull request closed without merging**
