### PR TITLE
Include documentation for toString function

### PR DESCRIPTION
**Pull request by Mats-SX**

### CODE REVIEW

**Comment by pontusmelke** [comment]
Is the test error caused by that `tostring.asciidoc` is already included in `/community/cypher/docs/cypher-docs/src/docs/dev/ql/functions/index.asciidoc`?

**Comment by pontusmelke** [comment]
Looking at the documentation I see that it is already included under `Scalar functions`, http://neo4j.com/docs/stable/query-functions-scalar.html

**Comment by nawroth** [comment]
@pontusmelke Good catch! The checks for such mistakes happens later in the build (so the resulting HTML and PDF become available sooner).

What's the difference between the `str` and `toString` functions?

**Comment by pontusmelke** [comment]
@nawroth If I have understood it correctly `toString`works only on numbers (and strings) while `str` gives you string representations of nodes and relationships _etc_

**Comment by Mats-SX** [comment]
@pontusmelke @nawroth This should now work.

**Pull request merged**
