### PR TITLE
Add possibility to select database edition dynamically in runtime

### PR DESCRIPTION
**Pull request by MishaDemianenko**
Add possibility to GraphDatabaseFactory to dynamically select database edition based on editions available in classpath.
Specific edition also can be forced by property.
Eliminates the need of custom Enterprise/HA/any other factories that just start appropriate edition.
Allows start of any edition by GraphDatabaseFactory only

### CODE REVIEW

**Comment by MishaDemianenko** [comment]
Hey @tinwelint, @lutovich what do you guys think about it as future enhancement? Current version only shows general principle and should only be considered as experimental/ show case

**Comment by benbc** [comment]
@MishaDemianenko I think this should go on 3.1 at this point, shouldn't it?

**Comment by MishaDemianenko** [comment]
@benbc that will not gonna go into 3.0 for sure, it's an experimental branch just to see how much we will gain using this approach.
please just ignore it's destination branch :)

**Comment by MishaDemianenko** [comment]
@tinwelint @lutovich do you have any feedback guys, did you have some time to look into it?

**Comment by systay** [comment]
@MishaDemianenko Is this still alive, or should we close the PR?

**Comment by MishaDemianenko** [comment]
@systay did not get any feedback yet, let me reping guys, thx

**Comment by MishaDemianenko** [comment]
@lutovich @tinwelint guys, do you have any feedback on it? do you think it's a good idea to do saw? (final warning otherwise it will die in limbo)

**Comment by MishaDemianenko** [comment]
It was decided that it makes not really clear what's happens behind in case of too generic factory.

**Pull request closed without merging**
