### PR TITLE
Introduce server-side cypher request timing

### PR DESCRIPTION
**Pull request by thobe**

### CODE REVIEW

**Comment by thobe** [comment]
The Browser can take advantage of this to show how much time a query spent on the server, discounting the time of the server (incoming) network stack.

**Comment by thobe** [comment]
If this passes review, @oskarhane would you please make the browser use this?

**Comment by pontusmelke** [comment]
Looks nice but there is some more mocking to be done in TransactionHandleTests…

**Comment by thobe** [comment]
I wonder if we might want to include a breakdown of timing included in the future. For example how much time was spent parsing, and how much time was spent planning et.c. If we want that we should prepare for it by changing the format from:
`"serverTimeNanos": <value>`
to something like:
`"executionTime": {"total": <value>}`

On the other hand, perhaps we would prefer to have that breakdown of time in the `profile` data instead.

**Comment by thobe** [comment]
@akollegger could you please comment on the structure of this result-data?

**Comment by akollegger** [comment]
@thobe Because this would be included on every request we should keep it to a minimum. I agree with your observation that a user who wants to know more should use `profile`. Even this much _could_ have a sideband switch to request the timing information. What do you think about adding that?

Otherwise, do you have some sense about the per-call impact? `nanoTime()` is more expensive than `currentTimeMillis()`, though probably negligible until vast numbers of concurrent calls. It's at worst an extra microsecond per call, right?

**Comment by thobe** [comment]
@akollegger the question is if we should make the format _accommodate_ for having those additional (optional) timing information entries in the same place, or if we think that (all of) those should be included _only_ in the profiling information.

This particular timing is tricky to include in the profiling information. Since we want it to measure as much of the execution as possible, we want to write it as late as possible.

We could add a switch for including this time, I opted not to, because I figured the overhead in terms of transfered bytes was low enough (as long as it is only a single time), and the overhead of checking for such a switch would be bigger than just doing the measurement.

In terms of cost `nanoTime()` is slightly more expensive than `currentTimeMillis()`, although I can usually squeeze a few (tens) of them into the same microsecond. So it is not an overhead that matters in the context. What does matter though is that nanosecond precision is most likely overkill for measuring these requests, since they typically take a few milliseconds.

**Comment by systay** [comment]
@akollegger where are we on this PR? yay or nay?

**Comment by jexp** [comment]
pretty please :)

**Comment by systay** [comment]
@akollegger Closing this PR for now. Please let us know if you want it in

**Comment by thobe** [comment]
@jexp did some testing to compare this server-side timing to client side timing, here are his findings:

```
retrieve all 189 nodes from localhost:
first run:  client side timing: 131ms, server side timing: 98ms  (network "overhead" = 33ms = 34%)
second run: client side timing:  47ms, server side timing: 12ms  (network "overhead" = 35ms = 292%)
```

```
retrieve all 189 nodes from a remote host (with 20ms ping):
first run:  client side timing: 136ms, server side timing: 63ms  (network "overhead" = 73ms = 116%)
second run: client side timing:  89ms, server side timing:  9ms  (network "overhead" = 80ms = 889%)
```

So the difference in between measuring time on the server, versus measuring on the client can be quite substantial.

@akollegger please take that into consideration in your decision process.

I think the main consideration for this feature is what the structure should look like for the returned time.

**Comment by jexp** [comment]
@akollegger also for other db's that do it: 

elasticsearch includes timing in a "took" property with every response. Also additionally a timed_out property.
https://www.elastic.co/guide/en/elasticsearch/reference/current/_the_search_api.html

**Pull request closed without merging**
