### PR TITLE
Stop clobbering System.out in the BoltKernelExtension

### PR DESCRIPTION
**Pull request by chrisvest**
Let's check the build log for any undesirable output once it's built, to make sure this doesn't open up any undesirable flood-gates of log spam. We only want desirable flood-gates of log spam.

### CODE REVIEW

**Comment by chrisvest** [comment]
No unwanted spam has been observed in the build log.

**Comment by MishaDemianenko** [comment]
LGTM!

**Comment by chrisvest** [comment]
@nigelsmall @zhenlineo @pontusmelke What do you think of this?

**Comment by chrisvest** [comment]
@nigelsmall @zhenlineo @pontusmelke Ping.

**Comment by zhenlineo** [comment]
LGTM.

**Pull request merged**
