### PR TITLE
Cypher cleanups

### PR DESCRIPTION
**Pull request by davidegrohmann**

### CODE REVIEW

**Comment by pontusmelke** [comment]
I am all for these changes, but at some point we said we should only fix bugs in maintenance releases? Have we changed our minds? Note also some of this is already fixed in 3.0.

**Comment by davidegrohmann** [comment]
@pontusmelke I might understand to avoid big changes in patch releases, but these are not really scary ones. Don't you think?

**Comment by pontusmelke** [comment]
Our discussion has been that we should only fix real problems in patch releases 
- The eagerness toVector fix could be argued to be a performance enhancement (already fixed in 3.0). I have not seen any complaints about this particular performance in 2.3 though.
- The other fix is clean up that does not give us any benefit in 2.3.

We have probably broke this rule lots of times already, but I think in general it is a good rule. Keeping changes to a minimum makes it easier to track regressions and minimizes the risk of introducing new ones. But as said we break it all the time and I like these changes so I am not going to be too hard headed about it. I'll leave it to @systay @craigtaverner @petraselmer @Mats-SX @henriknyman too decide

**Comment by systay** [comment]
I agree with you here, @pontusmelke. Once a branch is a maintenance branch, I rather not change anything in it unless it is prompted by a bugfix. I think these are nice fixes that should go in to 3.0

**Pull request closed without merging**
