### PR TITLE
Append character instead of string

### PR DESCRIPTION
**Pull request by asashour**
This makes a little better performance.

Also, when we have a StringBuilder, there is no need to create a new one by concatenating strings, instead `.append()` to the existing one is better.

### CODE REVIEW

**Review by klaren — APPROVED** [review]
While we might not be able to measure the performance gain it's still good practice. Thanks for the PR!

**Comment by klaren** [comment]
There are a couple of CI failures due to characters being added as a number and not a string with other numbers. As this will introduce possible problems when refactoring I think we will have to stick with strings. Since the benefits are not measurable I think that is the better option. And advances in the compiler should be able to do this automatically.

E.g.

```java
        out.println( currentStepIndex + '/' + totalSteps + ' ' + target );
```

This did not end up the way we wanted it with a `/` in the message.

**Comment by asashour** [comment]
I see, I should have run all tests, but it takes ages.

Would it be possible to reopen this if all tests pass locally?

**Comment by klaren** [comment]
We don't have high enough test coverage for me to be comfortable with such a change. You accidentally renamed all of our spawned threads and there is no test to validate that.

If you only change `StringBuilder` usages I think that should be fine, since you can't accidentally make it a number addition there.

**Pull request closed without merging**
