### PR TITLE
Add new store version, composite indexes

### PR DESCRIPTION
**Pull request by ragadeeshu**
We don't want people to open new stores with the new indexes with older Neo4j versions.
Also added a test that makes sure that no actual migration takes place.

### CODE REVIEW

**Review by tinwelint — CHANGES_REQUESTED** [review]
At first glance it looks like there were a lot of high limit format files copied and I don't see the apparent need for doing so. I may have missed something, but marking as request changes and ask for a description of why it's necessary.

**Review by tinwelint — APPROVED** [review]

**Comment by tinwelint** [comment]
For the record: It was decided to keep these copies since it goes in line with previous migrations. We can de-copy these as part of other work if needed.

**Comment by ragadeeshu** [comment]
@tinwelint rebased

**Comment by tinwelint** [comment]
@ragadeeshu compilation error

**Pull request merged**
