### PR TITLE
Remove HAS

### PR DESCRIPTION
**Pull request by pontusmelke**
`HAS` was deprecated in 2.3, let's remove it.

### CODE REVIEW

**Comment by boggle** [comment]
Last status on this was that it should be renamed to EXISTS, per CLG or did I get that wrong, @systay?

**Comment by pontusmelke** [comment]
@boggle I don't understand we already have `EXISTS`? `HAS` was deprecated in 2.3.

**Comment by boggle** [comment]
I haven't checked.. do we have both, EXISTS ( subquery ) and more importantly EXISTS ( expr ) that is basically has with a different name? If so, never mind my comment and proceed :)

**Comment by pontusmelke** [comment]
@boggle currently `HAS` is rewritten to `EXISTS` in all cases I believe. Both use the same `commands.predicates.PropertyExists` at runtime. Yes, `EXISTS` has all the functionalities `HAS` has (or had).

**Comment by boggle** [comment]
Sorry, I didn't know EXISTS( expr ) was already implemented.

**Pull request merged**
