### PR TITLE
Scala 2.11

### PR DESCRIPTION
**Pull request by tuxBurner**
Hi,

  i started lifting the cypher scala version from 2.10.4 to 2.11.1.
This wasn't as easy as I thought but I got it running. 
The main problem was that neo4j supports the old cypher versions, which where compiled with scala 2.10. 
I made a new project under **community/cypher/cypher-backport**, this contains the cyper-compilers: 1.9,2.0, and 2.1 which i tooked from the maint branches. Also they include the cypher-commons projects.
I added a new maven profile: **skipCypherBacports** to gain some compile time :)
It compiles at the moment with **mvn clean install -DskipTests -Dlicensing.skip**

The main drawback of this method is that the compile time is now huge. Perhaps in the future the  **skipCypherBacports** profile should be enabled by default.

### CODE REVIEW

**Comment by jexp** [comment]
Heya, thanks for your PR. Could you please sign and send in our CLA ?

http://neo4j.com/docs/stable/cla.html

Cheers

**Comment by tuxBurner** [comment]
Hey @jexp ,

 of course my friend :)

**Comment by tuxBurner** [comment]
@jexp got my signed CLA ?

**Comment by jexp** [comment]
Jep @nawroth has to add you somewhere now :)

**Comment by systay** [comment]
Hi @tuxBurner!

This is really great stuff! Sorry we have not responded earlier. 

To get this into a shape to be merged in, a little more work is remaining. I'll list it here.

#1. Since we will continue to support older maintenance branches, it would be nice if the updated compilers did not all live in one branch, and instead the new compilers could live with each respective branch? So the Cypher 2.1 compiler built for Scala 2.11 should live in the branch `2.1-maint`. 

#2. Could you please clean up the commits? Squash changes into bigger commits with better commit messages? And it's nice if you could rebase the work instead of merging in master on top of your changes - makes the git log so much nicer to read.

I've added you to the list of accepted contributors, so CI should be building the PR right now. 

Again - thank you so much for spending your time on this.

**Comment by systay** [comment]
Please re-open again if the branch gets updated.

**Pull request closed without merging**
