### PR TITLE
Provide sensible defaults for advertised addresses.

### PR DESCRIPTION
**Pull request by apcj**
The ability to configure advertised socket addresses is a useful
feature because it allows fine-tuning of network routing between
servers.

However, while this power is useful, there it is inconvenient
to have to always specifify the advertised addresses. For example,
to change the port for one of the protocol servers, two settings
need to be changed and kept in sync: both the listen and advertised
addresses.

This commit joins together the listen and advertised addresses
for each of the core-edge protocol servers, so that when the
advertised address is unspecified, a value can be derived by extracting
the port from the corresponding listen address. As well as a port,
a hostname is required, and this comes from a new global setting
dbms.network.advertised_hostname. There is no default value for
dbms.network.advertised_hostname; if unspecified then the setting
is derived by asking Java to resolve localhost, as was previously
used in HA networking. In a real multi-server deployment, a user
should explicitly set a real hostname that is resolvable in DNS.
When running multiple servers locally for testing, set it to
"localhost".
# Example configurations
## Cluster formed of independent dedicated servers

There is no need to specify listen addresses when running on independent hosts, because there will be no port conflicts. However, with the previous design it was necessary to configure the advertised addresses:

```
core_edge.transaction_advertised_address=server1.example.org:6001
core_edge.raft_advertised_address=server1.example.org:7400
```

```
core_edge.transaction_advertised_address=server2.example.org:6001
core_edge.raft_advertised_address=server2.example.org:7400
```

```
core_edge.transaction_advertised_address=server3.example.org:6001
core_edge.raft_advertised_address=server3.example.org:7400
```

With the new design, it's only necessary to set the advertised hostname; all the individual advertised addresses can be derived from the combination of this and the listen addresses:

```
dbms.network.advertised_hostname=server1.example.org
```

```
dbms.network.advertised_hostname=server2.example.org
```

```
dbms.network.advertised_hostname=server3.example.org
```

It's even possible to leave out this parameter altogether, if you are prepared to rely on `InetAddress.getLocalHost().getHostAddress()`.
## Testing cluster with all members on the same host

Previously config would always be required for both listen and advertised addresses to avoid port conflicts.

```
core_edge.transaction_listen_address=0.0.0.0:6000
core_edge.transaction_advertised_address=localhost:6000
core_edge.raft_listen_address=0.0.0.0:7400
core_edge.raft_advertised_address=localhost:7400
```

```
core_edge.transaction_listen_address=0.0.0.0:6001
core_edge.transaction_advertised_address=localhost:6001
core_edge.raft_listen_address=0.0.0.0:7401
core_edge.raft_advertised_address=localhost:7401
```

```
core_edge.transaction_listen_address=0.0.0.0:6002
core_edge.transaction_advertised_address=localhost:6002
core_edge.raft_listen_address=0.0.0.0:7402
core_edge.raft_advertised_address=localhost:7402
```

Now you can just specify the listen addresses, and (only once) specify the advertised hostname, e.g.:

```
dbms.network.advertised_hostname=localhost
core_edge.transaction_listen_address=0.0.0.0:6000
core_edge.raft_listen_address=0.0.0.0:7400
```

```
dbms.network.advertised_hostname=localhost
core_edge.transaction_listen_address=0.0.0.0:6001
core_edge.raft_listen_address=0.0.0.0:7401
```

```
dbms.network.advertised_hostname=localhost
core_edge.transaction_listen_address=0.0.0.0:6002
core_edge.raft_listen_address=0.0.0.0:7402
```

### CODE REVIEW

**Comment by benbc** [comment]
Does the advertised port default to the default port for that connector or the port of the listen address? It's not obvious to me which would more useful and/or less surprising.

**Comment by benbc** [comment]
Have you given up on using "_.connector.<name>._" for the core-edge stuff? Or just not made that change yet?

**Comment by benbc** [comment]
What's the proposed default listen address hostname? `InetAddress.getLocalHost().getHostAddress()`? `localhost`? `0.0.0.0`?

**Comment by benbc** [comment]
Example for configuring multiple Neo4j Docker containers running on the same host.

Container 1:

```
dbms.network.listen_address=0.0.0.0
dbms.network.advertised_address=the.host.address
core_edge.transaction_advertised_address=:1000
core_edge.raft_advertised_address=:1001
```

Container 2:

```
dbms.network.listen_address=0.0.0.0
dbms.network.advertised_address=the.host.address
core_edge.transaction_advertised_address=:1002
core_edge.raft_advertised_address=:1003
```

Host port mappings:

```
1000 -> container1:6000
1001 -> container1:7400
1002 -> container2:6000
1003 -> container2:7400
```

**Comment by apcj** [comment]
superseded by https://github.com/neo4j/neo4j/pull/7855

**Pull request closed without merging**
